### ISSUE TITLE
Private API usage ? Can this framework be compatible with App Store Submit Rule ?

### ISSUE THREAD

**Issue by dreampiggy** [siteline/SwiftUI-Introspect#1]
Just a little cruious about use case. Is this a debug helper tool, or ready for some real world use case for production.

**Comment by ldiqual** [comment]
Introspect is meant to be used in production apps. It is not a debugging tool. Definitely wouldn't say that it's battle-tested though, as we introduced it at Timber only a week ago and it didn't make it to production yet.

Introspect does not use private APIs, all it does is inspect the view hierarchy using publicly available SDK methods. Almost positive it would pass Apple's review system.

**Comment by ldiqual** [comment]
I think it is likely to be a frequently asked question, so I'll add a section in the README and close this issue. Thanks for the push!

**Comment by ldiqual** [comment]
Addressed in 6688ebe

**Comment by dreampiggy** [comment]
This code using a private Class symbol : `UIHostingView`, which is not a public API.
https://github.com/timbersoftware/SwiftUI-Introspect/blob/master/Introspect/Introspect.swift#L66

But actually, I've already using little private API in production App. For suggestion, you should encrypt the raw string symbol, for example, using Base-64 Encoded string, decode in runtime, and then call that `NSClassFromString` instead. I'm here to just point out the potential risk.

Apple's machine detection of Private API does not only check the linked symbol in Mach-O, also with some smart detection of raw string, runtime linked framework check. So it's better to take care.

**Comment by ldiqual** [comment]
@dreampiggy That's a really good point, I never considered the fact that simply checking for the class name of an instance could trigger their private symbol detection. Would changing the relevant string to just `HostingView` be safer? I don't want to purposely hide what the code is doing, it would be bad faith on our part, while all we're trying to do is inspect the view hierarchy, not use private frameworks / APIs.

**Comment by yonaskolb** [comment]
While the above questions are being answered it would be good to know if any builds have actually made it into the app store

**Comment by yonaskolb** [comment]
Any news on this?

**Comment by ldiqual** [comment]
Nothing on Timber's end. We haven't published the app to the App Store yet and it won't happen for another couple of weeks since we're in very early stages.

**Comment by ribilynn** [comment]
My app [DereGuide2](https://apps.apple.com/us/app/%E3%83%87%E3%83%AC%E3%82%AC%E3%82%A4%E3%83%89-2-for-%E3%83%87%E3%83%AC%E3%82%B9%E3%83%86/id1493630000) using this framework(to just remove tableView's separator) was published to App Store. So there is no problem.

**Comment by dreampiggy** [comment]
Seems this can be closed.
