### ISSUE TITLE
Animations break instrospectScrollview ?

### ISSUE THREAD

**Issue by Saturnyn** [siteline/SwiftUI-Introspect#109]
Hi,
I'm working on a fairly complex SwiftUI app that relies on instrospectScrollView a lot.
The structure of the app is something like this:
- the navigation is done using tabs to switch between the app pages
- each page contains a ScrollView and an instrospectScrollView() call to get a ref on the UIScrollView
- there is a fixed header that is displayed on top of everything else

It works fine: whenever I switch tab, I can see that instrospectScrollView() is called and I can control the scroll with this.
However, **if I add a SwiftUI animation in my header, instrospectScrollView() stops working**. Everything else is fine, but I don't get a ref on the UIScrollView anymore.

I tried looking into the issue, using the same method I did for https://github.com/siteline/SwiftUI-Introspect/issues/73 by printing the whole view hierarchy inside the instrospectScrollView() call to see why the HostingScrollView can't be found. Turns out it is not present at all. My guess is that having the animation running messes with the hierarchy somehow and introduces some kind of delay ?

Anyway, I don't think this description is clear enough, so I made a demo to show the problem:

```
import SwiftUI
import Introspect

struct ContentView: View {
	@State var showScrollView:Bool = false
	@State var showAnim:Bool = false
	@State var didIntrospectScrollView = false
	@State var scrollY:CGFloat = 0
	@State var rotate:Bool = false
	
	var body: some View {
		VStack{
			HStack{
				//Testing UI
				VStack(alignment: .leading){
					Toggle("Show scrollview", isOn: $showScrollView)
					Toggle("Show anim", isOn: $showAnim)
					
					Text("didIntrospectScrollView: ") + Text("\(didIntrospectScrollView ? "true":"false")").bold()
				}
				.frame(maxWidth: 300)
			
				Spacer()
				
				if self.showAnim {
					//A perpetually animated view
					Color.red.frame(width:50, height: 50)
					.rotationEffect(Angle(degrees: self.rotate ? 360.0 : 0.0), anchor: .center)
					.animation(
						Animation.linear(duration: 2.0)
						.repeatForever(autoreverses: false),
						value: rotate
					)
					.onAppear{
						self.rotate = true
					}
					.onDisappear{
						self.rotate = false
					}
				}
			}
			.background(Color.black.opacity(0.2))
			.padding(.bottom, 10)
			
			
			if showScrollView{
				ScrollView{
					VStack{
						ForEach((1...50), id: \.self) {
							item($0)
						}
					}
				}
				.introspectScrollView{ scrollView in
					didIntrospectScrollView = true
				}
				.onDisappear(){
					self.didIntrospectScrollView = false
				}
				.background(Color.red)
			}else{
				Spacer()
				Text("No scroll view")
				Spacer()
			}
		}
	}
	
	func item(_ value:Int)->some View{
		HStack{
			Text("\(value)")
			Spacer()
		}
		.border(Color.red)
		.padding(10)
	}
}

```

You can see the problem like this:
- activate / deactivate "Show scrollview" a few times. You should see that when the red scroll view appears, "didIntrospectScrollView" is set to true indicating the introspectScrollview() call works as expected
- then, activate "Show anim", it only adds a rotating square in the header
- activate / deactivate "Show scrollview" a few times. You should see that "didIntrospectScrollView" now stays false all the time.

**Comment by jlott1** [comment]
@Saturnyn I was just curious about this issue,  I took your code and ran it in the simulator but I still see `didIntrospectScrollView = true` getting called even with the animation on.  I'm on Xcode 12.4 with iOS 14 simulator.  I also see this `introspectScrollView()` getting called when toggling the switch off to hide the scroll view.

**Comment by Saturnyn** [comment]
Hi, to be honest I haven't even tried running this in the simulator, as I find it to be not reliable at all when trying to debug this kind of SwiftUI issues. 
For the moment I've only tried this on an actual iPad, so I'm curious to know if you're able to reproduce the problem on other physical devices.

**Comment by cerupcat** [comment]
I appear to be able to produce the same on a real device.

**Comment by davdroman** [comment]
Happy to report this is no longer an issue when using the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module:

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    @State var showScrollView:Bool = false
    @State var showAnim:Bool = false
    @State var didIntrospectScrollView = false
    @State var scrollY:CGFloat = 0
    @State var rotate:Bool = false

    var body: some View {
        VStack{
            HStack{
                //Testing UI
                VStack(alignment: .leading){
                    Toggle("Show scrollview", isOn: $showScrollView)
                    Toggle("Show anim", isOn: $showAnim)

                    Text("didIntrospectScrollView: ") + Text("\(didIntrospectScrollView ? "true":"false")").bold()
                }
                .frame(maxWidth: 300)

                Spacer()

                if self.showAnim {
                    //A perpetually animated view
                    Color.red.frame(width:50, height: 50)
                    .rotationEffect(Angle(degrees: self.rotate ? 360.0 : 0.0), anchor: .center)
                    .animation(
                        Animation.linear(duration: 2.0)
                        .repeatForever(autoreverses: false),
                        value: rotate
                    )
                    .onAppear{
                        self.rotate = true
                    }
                    .onDisappear{
                        self.rotate = false
                    }
                }
            }
            .background(Color.black.opacity(0.2))
            .padding(.bottom, 10)


            if showScrollView{
                ScrollView{
                    VStack{
                        ForEach((1...50), id: \.self) {
                            item($0)
                        }
                    }
                }
                .introspect(.scrollView, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { scrollView in
                    didIntrospectScrollView = true
                }
                .onDisappear(){
                    self.didIntrospectScrollView = false
                }
                .background(Color.red)
            }else{
                Spacer()
                Text("No scroll view")
                Spacer()
            }
        }
    }

    func item(_ value:Int)->some View{
        HStack{
            Text("\(value)")
            Spacer()
        }
        .border(Color.red)
        .padding(10)
    }
}
```

Cool repro btw, quite creative 😄
