### ISSUE TITLE
.introspectTextField not working on macOS

### ISSUE THREAD

**Issue by pmmlo** [siteline/SwiftUI-Introspect#113]
No issues with iOS, macOS Catalyst, or iPadOS, but .introspectTextField does not fire on macOS.  Anybody else experiencing this?

```
TextField("Text Here", text: self.$text).introspectTextField { tF in
    print("foobar") // <-- Never fires.
    tf.becomeFirstResponder()
}
```

**Comment by bryan1anderson** [comment]
Same thing but on iOS

**Comment by rp779** [comment]
@bryan1anderson did you get it to work?

**Comment by GeorgeElsham** [comment]
@pmmlo Works for me, Introspect version `0.1.3`. Could be on my part trying to reproduce the issue?

**Comment by egistli** [comment]
@GeorgeElsham
I can confirm this might be an issue for version earlier than 0.1.3. 
I have this issue at 0.1.2 and it works after upgrading to 0.1.4.

**Comment by davdroman** [comment]
Here's the how you accomplish this across iOS and macOS using the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module:

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    @State var text = ""

    var body: some View {
        TextField("Text Here", text: $text)
            #if os(iOS) || os(tvOS)
            .introspect(.textField, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { textField in
                print("foobar")
                DispatchQueue.main.async {
                    textField.becomeFirstResponder()
                }
            }
            #elseif os(macOS)
            .introspect(.textField, on: .macOS(.v10_15, .v11, .v12, .v13, .v14)) { textField in
                print("foobar")
                DispatchQueue.main.async {
                    textField.becomeFirstResponder()
                }
            }
            #endif
    }
}
```

##### PS: note that while `DispatchQueue.main.async` is used, it works just fine without it but it throws a runtime warning.
