### ISSUE TITLE
PaginationView - turn off programmatic page index change animation

### ISSUE THREAD

**Issue by geraldvoit** [siteline/SwiftUI-Introspect#118]
Hi, in my application there is a use-case where the PaginationView should not animate between pages when the page index is manipulated programmatically, but sometimes it should. Scrolling between pages should be possible although. Therefore, I'm wondering if there is an easy way to expose an API for this case? Like "shouldAnimate" as shown in the code snippet below.

```
PaginationView(axis: .vertical, showsIndicators: false) {
                ForEach(subpages) { subpage in
                    ...
                }
}
.currentPageIndex(subpageIndexBinding)
.shouldAnimate(viewModel.shouldAnimate)
```

**Comment by jevonmao** [comment]
What's even a `PaginationView`? Is it a custom SwiftUI view component? Does it involve any UIKit?

**Comment by geraldvoit** [comment]
So sorry, I messed up my browser tabs and opened the issue here instead of https://github.com/SwiftUIX/SwiftUIX .
