### ISSUE TITLE
 .introspectTextField is not getting called

### ISSUE THREAD

**Issue by rp779** [siteline/SwiftUI-Introspect#119]
if isEditingTableNumber {
            TextField("", text: $tableNumber)
                  .keyboardType(.numberPad)
                  .font(.custom(Font.regular_400, size:17))
                  .foregroundColor(Colors.text)
                  .introspectTextField {      textField in
                            print("--------------foobar")
                            textField.becomeFirstResponder()
             }
    }

`isEditingTableNumber` is a `@State` variable that is toggled by a button in the same `HStack`

"foobar" is never printed and the `TextField` does not become the first responder.

**Comment by JetForMe** [comment]
Same for me, in this code:
```swift
TextField("Email", text: self._address)
	.introspectTextField {
		$0.becomeFirstResponder()
	}
	.textFieldStyle(RoundedBorderTextFieldStyle())
	.keyboardType(.emailAddress)
```

iOS 14.7.1 on an iPhone SE, inside a [PartialSheet](https://github.com/AndreaMiotto/PartialSheet), Xcode 12.5.1.

**Comment by gongzhang** [comment]
Just found out: adding a `brightness` modifier to the outer layer will prevent introspect.

```swift
TextField("Text", text: .constant("Hello"))
                    .introspectTextField { textField in
                        // never called
                    }
                    .brightness(0.1) // <- this causes introspection to fail
```

**Comment by yspreen** [comment]
I don't have any brightness modifiers. I even put the TextField in an empty VStack container to get rid of any modifiers it might have. It does have `axis: .vertical` though, maybe that's the problem. Regardless, I cannot get the introspection to call

**Comment by samhenrigold** [comment]
`axis: .vertical` seemed to be the problem for me, removing the modifier fixed it 😕
