### ISSUE TITLE
introspectSplitViewController(customize:) not available

### ISSUE THREAD

**Issue by alobaili** [siteline/SwiftUI-Introspect#121]
I'm trying to customize the underlying `UISplitViewController` of a `NavigationView` with `DoubleColumnNavigationViewStyle`, but the function `introspectSplitViewController(customize:)` is not showing in autocomplete and even if I manually type it in full,  I get  a compiler error that it's not found.

The readme file says it's available for `SwiftUI.NavigationView`, but I can seem to find a way to call it.

I'm using version 0.1.3 of the package.

Any help is appreciated.

**Comment by SplittyDev** [comment]
I see, I just checked the changelog and it seems that this change hasn't made it into a release yet.
I'm gonna try to get a release going 👍

**Comment by briannadoubt** [comment]
Any progress on this? Would be LOVELY to be able to make a real split view experience.

**Comment by alobaili** [comment]
While I haven't tested it yet. It appears that version 0.1.4 released 2 days ago fixes this issue! 😃
https://github.com/siteline/SwiftUI-Introspect/releases/tag/0.1.4

@ldiqual @SplittyDev If you can confirm this. I think we can close this issue.

**Comment by davdroman** [comment]
Here's how to do this with the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module:

### NavigationView

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    var body: some View {
        NavigationView {
            ZStack {
                Color.red
                Text("Something")
            }
        }
        .navigationViewStyle(DoubleColumnNavigationViewStyle())
        .introspect(.navigationView(style: .columns), on: .iOS(.v13, .v14, .v15, .v16, .v17)) { splitViewController in
            print(type(of: splitViewController)) // UISplitViewController
        }
    }
}
```

### NavigationSplitView

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    var body: some View {
        NavigationSplitView {
            ZStack {
                Color.red
                Text("Root")
            }
        } detail: {
            ZStack {
                Color.blue
                Text("Detail")
            }
        }
        .introspect(.navigationSplitView, on: .iOS(.v16, .v17)) { splitViewController in
            print(type(of: splitViewController)) // UISplitViewController
        }
    }
}
```
