### ISSUE TITLE
Scroll view: scroll indicator insets not honored (but content inset is)

### ISSUE THREAD

**Issue by cyrillelegrand** [siteline/SwiftUI-Introspect#123]
On iOS 14 and on iOS 15, I have the same problem: I can't change the scroll indicator insets.

```
.introspectScrollView {
    $0.contentInsetAdjustmentBehavior = .never
    $0.automaticallyAdjustsScrollIndicatorInsets = false
    let Δ = UIApplication.shared.windows.first?.safeAreaInsets.top ?? 0
    $0.contentInset = .init(top: Δ, left: 0, bottom: 0, right: 0)
    $0.scrollIndicatorInsets = .init(top: Δ, left: 0, bottom: 0, right: 0)
    print("Top padding: \(Δ)")
}
```

Δ is 44 on an iPhone X; the contentInset is honored, but the scrollIndicatorInsets are not (even though I disabled automatic adjustments as you can see).
This may well be a bug of SwiftUI itself where it takes precedence.

**Comment by keremcesme** [comment]
Can you share if you found any solution? @cyrillelegrand

**Comment by helfi2012** [comment]
@keremcesme The solution is to use `verticalScrollIndicatorInsets`:
```
.introspectScrollView { scrollView in
    scrollView.verticalScrollIndicatorInsets.top = 10
    scrollView.verticalScrollIndicatorInsets.bottom = 40
}
```
Tested only on iOS 15.
