### ISSUE TITLE
introspectTableView bug on iOS 15

### ISSUE THREAD

**Issue by ahmetws** [siteline/SwiftUI-Introspect#127]
Hi,

I have a case where this code disables the scroll on <15 but doesn't work on iOS 15 beta.

`
List {
  ...
}
.introspectTableView { tableView in
  tableView.isScrollEnabled = false
}
`

If I tried to change the background color `tableView.backgroundColor = .red`, it works on iOS 15.

Is it possible that the scroll API is changed on iOS 15?

**Comment by davdroman** [comment]
Can't reproduce with the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module so I think this might not be an issue anymore in the new implementation:

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    var body: some View {
        NavigationView {
            List {
                Text("List")
            }
            .introspect(.list, on: .iOS(.v13, .v14, .v15)) { tableView in
                tableView.isScrollEnabled = false
            }
            .introspect(.list, on: .iOS(.v16, .v17)) { collectionView in
                collectionView.isScrollEnabled = false
            }
        }
    }
}
```
