### ISSUE TITLE
Disabling `isScrollEnabled` for List inside nested inside a ScrollView doesn't work on iOS 15

### ISSUE THREAD

**Issue by nagra** [siteline/SwiftUI-Introspect#128]
Hi,

I am trying to disable the scrolling of a nested List view inside a ScrollView.
I wanted to disable scrolling, but still require the tap events to work so a detail view can be shown.
The parent ScrollView houses other ScrollView's which scroll horizontally i.e.

```
ScrollView {
                
    ScrollView {}
                
    ScrollView {}
                
    List {
                    
    }.introspectTableView { tableView in
        tableView.isScrollEnabled = false
    }
}
```

The code seems to work fine on iOS 14 and below, but stopped working in iOS 15 (currently beta 8). 
Any help would be much appreciated.

Thanks,
Kam

**Comment by DevonJerothe** [comment]
Hello, I am facing the same issue. Has any progress been found?

**Comment by nagra-gs** [comment]
We got round this by setting the height of the List the same height (or bigger) as the scrollView. 

That way the List scroll doesn't need to be disabled and the List events still get passed through.

**Comment by nagra-gs** [comment]
> so why you use List inside a scrollView

If you wanted a design where the overall content is scrollable, but part of it you wanted to be in the insetGrouped style, then you'd need a List inside a scroll view.

**Comment by nagra** [comment]
We got round this by setting the height of the List the same height (or bigger) as the scrollView.

That way the List scroll doesn't need to be disabled and the List events still get passed through.

**Comment by nagra** [comment]
> so why you use List inside a scrollView

If you wanted a design where the overall content is scrollable, but part of it you wanted to be in the insetGrouped style, then you'd need a List inside a scroll view.

**Comment by okmyself** [comment]
Sorry I've never used the insetGrouped style in SwiftUI, but can't achieve a similar effect with VStack/LazyVStack?

**Comment by davdroman** [comment]
Practicality aside, you'll find the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module is able to introspect nested views without ambiguity:

```swift
import SwiftUI
import SwiftUIIntrospect

struct ContentView: View {
    var body: some View {
        ScrollView {
            ScrollView {
                Text("ScrollView")
            }

            ScrollView {
                Text("ScrollView")
            }

            List {
                Text("List")
            }
            .listStyle(.plain)
            .frame(height: 100)
            .introspect(.list, on: .iOS(.v13, .v14, .v15)) { tableView in
                tableView.isScrollEnabled = false
            }
            .introspect(.list, on: .iOS(.v16, .v17)) { collectionView in
                collectionView.isScrollEnabled = false
            }
        }
    }
}
```
