### ISSUE TITLE
Introspect for text field

### ISSUE THREAD

**Issue by reinaldoriant** [siteline/SwiftUI-Introspect#131]
Hi, I want to change the return key with this. but it can't to change in iOS 14. Any Suggestion? Below is my code
`
                            TextField("", text: self.$searchVM.searchQuery, onCommit: {
                                self.ganti.toggle()
                            })
                                .keyboardType(.default)
                                .introspectTextFieldd{ (textField) in
                                    textField.returnKeyType = .search
                                }`

**Comment by ben73** [comment]
Today I faced the same problem.
 The solution is to use Introspect from the master branch. This bug seems to have been fixed in https://github.com/siteline/SwiftUI-Introspect/pull/83 , but there has been no release so far (no tag contains this commit at the moment).

**Comment by BilalMustafa** [comment]
@ben73 Thanks, Using the master branch resolved the problem.
