### ISSUE TITLE
introspectTableView - background color not being set in iOS 15

### ISSUE THREAD

**Issue by TheGeekPharaoh** [siteline/SwiftUI-Introspect#135]
I have a SwiftUI List that I am attempting to introspect so I can set the background color.  The code looks similar to this:

```
List {
  ...
}
        .listStyle(SidebarListStyle())
        .accentColor(.white)
        .introspectTableView { tableView in
            tableView.backgroundColor = UIColor(Color.orange)
        }
```

On iOS 14 this produces the desired outcome and gives me an orange background on the list.  On iOS 15, however, it does not.  I have set a breakpoint on the introspect body and in iOS 14 it is being triggered, but in iOS 15 it is not, so clearly the code is not even being called.

**Comment by Utsira** [comment]
In iOS15 you can do this natively with SwiftUI. Just use the `.background(Color.blue)` modifier on the List. For iOS 14 you still need to introspect. I find it useful to have conditional backfills for this kind of thing. eg

**Comment by honkmaster** [comment]
@Utsira You may be right for the .plain list style. However, this does not work for other styles like SidebarListStyle and / or InsetGroupedListStyle.

**Comment by theedov** [comment]
> In iOS15 you can do this natively with SwiftUI. Just use the `.background(Color.blue)` modifier on the List. For iOS 14 you still need to introspect. I find it useful to have conditional backfills for this kind of thing. eg
> 
> ```
> public extension View {
> 
> 	func listBackgroundColor(_ color: UIColor) -> some View {
> 		Group {
> 			if #available(iOS 15.0, *) {
> 				background(Color(color)) // doesn't work on iOS 14
> 			} else {
> 				introspectTableView {
> 					$0.backgroundColor = color
> 				}
> 			}
> 		}
> 	}
> }
> ```

I don't think .background() modifier on a List does what you say it does. 
In iOS16 they introduced `scrollContentBackground ` for this.

Btw. have the same issue:

```
.introspectTableView { tableView in
    tableView.backgroundColor = .red
}
```

^ Doesn't work.

**Comment by Mcrich23** [comment]
@theedov Did you find an answer?

**Comment by theedov** [comment]
> @theedov Did you find an answer?

No, not really, I just switched to iOS16+

I think Lists are now powered by the UICollectionView instead of UITableView.  So changing `UICollectionView.appearance()` might work(haven't tried it).

**Comment by davdroman** [comment]
See https://github.com/siteline/SwiftUI-Introspect/issues/110#issuecomment-1611835461 for a working solution.
