### ISSUE TITLE
Refresh control not working when added to introspected ScrollView without NavigationView

### ISSUE THREAD

**Issue by bbauman1** [siteline/SwiftUI-Introspect#136]
A standalone ScrollView with an introspected refresh control has an issue where the refresh control will move upwards on the y axis after pulling to refresh, making it unusable.

Example code:

```
var body: some View {
    ScrollView {
        LazyVStack {
            ForEach(Range(0...100)) { index in
                Rectangle()
                    .fill(index % 2 == 0 ? Color.green : Color.blue)
                    .frame(width: UIScreen.main.bounds.width,  height: UIScreen.main.bounds.height / 2)
            }
        }
    }
    .introspectScrollView { scrollView in
        guard scrollView.refreshControl == nil else { return }
        scrollView.refreshControl = UIRefreshControl()
    }
}
```

However, if the above code is wrapped in a `NavigationView` it behaves as expected. Does anyone know any other workarounds? I can't use a `NavigationView` in my implementation due to using a custom nav bar.

I also tried setting fixed constraints on the position of the refresh control within the scrollview, but that doesn't really work since the content of the scrollview will cover the refresh control while loading.

**Comment by keremcesme** [comment]
Can you share if you found any solution? @bbauman1

**Comment by bbauman1** [comment]
I haven't looked at it in a few months but I don't think its possible. I ended up tracking scroll offset and using a custom spinner view. Its not perfect though.

**Comment by davdroman** [comment]
See https://github.com/siteline/SwiftUI-Introspect/issues/176#issuecomment-1611807431 for solution.
