### ISSUE TITLE
Character input shifts back to initial textfield when using multiple text fields

### ISSUE THREAD

**Issue by SAPIENTechnologies** [siteline/SwiftUI-Introspect#14]
So I am using this package with multiple text fields in a SwiftUI form. When the form starts up, the first textfield becomes the first responder and all is good. I type in that field then press TAB to get to next field. As soon as I start typing, the caret moves to the original field and characters get typed in that field rather than the field I tabbed to.

Here is the snippet of code that uses the introspection call:

`                VStack(alignment: .leading) {
                    Text("Task name:")
                    TextField("Enter a name for this task", text: $task.name)
                        .formTextField(.words)
                        // using the Introspect Package
                        .introspectTextField { textField in
                            textField.becomeFirstResponder()
                        }
                }
                VStack(alignment: .leading) {
                    Text("Section name:")
                    TextField("Enter a name for this task's section", text: $task.group)
                        .formTextField(.words)
                }
`

**Comment by KonstantinEfimenko** [comment]
Currently using of version 0.0.6 can help

**Comment by SplittyDev** [comment]
Can't reproduce this on `master`.
Your view is probably updating when it shouldn't, this is not an issue caused by Introspect though.
