### ISSUE TITLE
Introspect TextEditor won't work in iOS 15

### ISSUE THREAD

**Issue by X901** [siteline/SwiftUI-Introspect#142]
Hi,
I tried to disable scrolling and editing in TextEditor 
it wasn't work at all !

I still can edit text and scrolling !

```
    TextEditor(text: .constant(text))
            .introspectTextView { textView in
                textView.isEditable = false
                textView.isScrollEnabled = false
            }
```

**Comment by ZsoltMolnarMBH** [comment]
Hello!
I am trying to change keyboard return type, but doesn't work either.

**Comment by X901** [comment]
is there any change to fix this issue ?

**Comment by davdroman** [comment]
Hi @X901. Are you still experiencing this issue with the latest `master`? I'll be closing it for now to keep our backlog tidy, but feel free to reopen it if so.
