### ISSUE TITLE
Can't use Introspect with "Blur"

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [siteline/SwiftUI-Introspect#154]
When we try use blur on the screen where Introspect, our introspect is broken
Example: 
`VStack {
            ScrollView {
                ForEach(0..<10) { _ in
                    Color.gray
                }
            }
            .introspectScrollView { scroll in
                scroll.contentInset.top = 150
            }
        }
        .blur(radius: 5)`

**Comment by davdroman** [comment]
@MaksimBezdrobnoi this is now fixed when using the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module:

```swift
struct ContentView: View {
    var body: some View {
        VStack {
            ScrollView {
                ForEach(0..<10) { _ in
                    Color.gray
                }
            }
            .introspect(.scrollView, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { scrollView in
                scrollView.backgroundColor = .red
            }
        }
        .blur(radius: 5)
    }
}
```
