### ISSUE TITLE
introspectNavigationController

### ISSUE THREAD

**Issue by rzil** [siteline/SwiftUI-Introspect#156]
In our project all the following are failing on an iPhone 6S device running iOS 15.1. Using Introspect v0.1.4.
`introspectNavigationController`
`introspectTabBarController`
`introspectScrollView`
They never trigger the callback. It works on other more recent devices, however. Is this a known issue?

**Comment by davdroman** [comment]
This is no longer an issue when using the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module. Closing.
