### ISSUE TITLE
View Controller Introspection is Inconsistent

### ISSUE THREAD

**Issue by rzulkoski** [siteline/SwiftUI-Introspect#166]
I have determined there is a timing issue present when attempting to introspect a UIKit view controller.

Sometimes when `UIKitIntrospectionViewController. updateUIViewController(_:context:)` is called the view controller's parent is not set yet and its view is not in the view hierarchy yet (hasn't been added to the window). This means that there are times when the customization never gets applied because the selector failed to find the target.

`UIKitIntrospectionView` works around this issue by applying the customizations as part of a `moveToWindowHandler` set on the `IntrospectionUIView`.

I was able to fix this issue by updating `UIKitIntrospectionViewController` to also use its view's `moveToWindowHandler` when apply customizations. In addition, I updated both `UIKitIntrospectionView` and `UIKitIntrospectionViewController` to set their handlers up front in their respective `makeUIView(Controller)` methods rather than delaying it until `updateUIView(Controller)` is called.

See pull request #165

**Comment by rzulkoski** [comment]
This has now been fixed. Thanks for getting this across the finish line @davdroman!

**Comment by davdroman** [comment]
@rzulkoski no worries! I'll do some CI maintenance over the weekend and tag a new release by Monday.
