### ISSUE TITLE
Missing VideoPlayer introspection

### ISSUE THREAD

**Issue by dev-jiwon** [siteline/SwiftUI-Introspect#167]
SwiftUI: VideoPlayer
UIKit: AVPlayerViewController

**Comment by davdroman** [comment]
@dev-jiwon apologies for the massive delay. This will ship with the [new `SwiftUIIntrospect` module](https://github.com/siteline/SwiftUI-Introspect/blob/master/docs/SwiftUIIntrospect.md) in the next release (0.7.0) in the next couple of days.
