### ISSUE TITLE
iOS 16 UIRefreshControl() inside introspectTableView stopped working

### ISSUE THREAD

**Issue by pbrns** [siteline/SwiftUI-Introspect#172]
Hi,

I noticed that in the iOS 16 the Refresh Control inside a introspectTableView stopped working.
`.listStyle(PlainListStyle())
                            .introspectTableView { tableView in
                                let control = UIRefreshControl()`
So now when I pull down to refresh nothing happens and no refresh controls appears. In iOS 15 it works ok.

**Comment by hmlongco** [comment]
in iOS 16 lists and form views are now back by collection views. They're no longer table views.

**Comment by pbrns** [comment]
So does this means that .introspectTableView will need to be removed and replaced from something different?

**Comment by pbrns** [comment]
The problem is if you app supports < iOS 15
Because in iOS 15 you have the refreshable in lists.

So it seems that is a good idea to have a check `if #available(iOS 15.0, *) {`
and use the` list.refreshable {**`
and if you are running before iOS 15 to keep having the UIRefreshControl inside the .introspectTableView

**Comment by Rex-xingjl** [comment]
How to change the header view when refreshing? This's not cool when use '**.refreshable**' with a de-ugly-ad activity Indicator

**Comment by svenoaks** [comment]
> So does this means that .introspectTableView will need to be removed and replaced from something different?

UICollectionView is a subclass of UIScrollView, but `introspectScrollView()` doesn't seem to work on List anymore either. Maybe it just needs to be updated.

**Comment by davdroman** [comment]
`introspectCollectionView` is now upstream (#169) and will soon be in a tagged release.
