### ISSUE TITLE
`.cornerRadius` parent breaks introspection.

### ISSUE THREAD

**Issue by lhunath** [siteline/SwiftUI-Introspect#174]
Strangely, when you apply a `.cornerRadius`, even outside in an parent view, the introspection stops working:
```
struct Preview: PreviewProvider, View {
    static var previews = Self()
    
    var body: some View {
        VStack {
            ScrollView {
                Text("Hello world!")
            }
            .introspectScrollView {
                $0.isScrollEnabled = false
            }
        }
        .background(Color.red)
        .cornerRadius(20)
    }
}
```

I expect the "Hello world!" to not be draggable, but it is. The introspection closure is never called.

**Comment by esmondmissen** [comment]
.clipped and .mask also breaks

**Comment by Toren4ik** [comment]
The same for shadow.

**Comment by davdroman** [comment]
@Toren4ik thanks for pointing out this workaround. I'm currently investigating ways of strengthening the library's logic in this regard. Definitely a tricky area though.

**Comment by Psli** [comment]
+1

**Comment by paescebu** [comment]
I thinksame issue as:
https://github.com/siteline/SwiftUI-Introspect/issues/162

would be fixed with this PR:
https://github.com/siteline/SwiftUI-Introspect/pull/213

Let me know if it would do it :)

**Comment by Psli** [comment]
> I think it's the same issue as: #162
> 
> would be fixed with this PR: #213
> 
> Let me know if it would do it :)

Similar issues can be seen in components like introspectTextView, introspectTextField and others.

> a temporary fix: [#73 (comment)](https://github.com/siteline/SwiftUI-Introspect/issues/73#issuecomment-782128575)

**Comment by paescebu** [comment]
@Psli lets see if my PR is accepted, if it is i'm happy to tackle also the other components in a similar fashion, so that they at least temporarily work. @davdroman seems to have bigger plans for a more stable API, that will maybe make all of those patches obsolete :)

**Comment by paescebu** [comment]
@davdroman sounds like a very solid plan, like it
