### ISSUE TITLE
iOS 16 introspectTableView stopped working

### ISSUE THREAD

**Issue by SAleksiev** [siteline/SwiftUI-Introspect#175]
For part of my code related to the pagination implementation I use the following:
```
.introspectTableView(customize: { tableView in
tableView.delegate = viewModel
})
```

It looks like for iOS 16 that's not working anymore ...

**Comment by constantine-fry** [comment]
It appears that List view uses collection view now (at least with some configurations). You can add the following extension into your project and use it to get the underlying collection view:

```
extension View {
  public func introspectCollectionView(customize: @escaping (UICollectionView) -> ()) -> some View {
    introspect(selector: TargetViewSelector.ancestorOrSiblingContaining, customize: customize)
  }
}
```

**Comment by davdroman** [comment]
`introspectCollectionView` is now upstream (#169) and will soon be in a tagged release.
