### ISSUE TITLE
Bug: introspectScrollView and  refreshControl 

### ISSUE THREAD

**Issue by hoangnam714** [siteline/SwiftUI-Introspect#176]
padding content is abnormal when I do pull to refresh content
my code here, 
```
import Foundation
import SwiftUI
import Introspect

struct CustomScrollView<Content: View>: View {
    var content: Content
    var refreshable: ()->Void
    let reFreshHelper = RefreshHelper()

    init( refreshable: @escaping () -> Void ,@ViewBuilder content: () -> Content) {
        self.refreshable = refreshable
        self.content = content()
    }

    var body: some View {
        ScrollView(.vertical){
            content
        }
        .introspectScrollView { scrollview in
            let control = UIRefreshControl()
            reFreshHelper.parent = self
            reFreshHelper.refreshControl = control
            control.addTarget(reFreshHelper, action: #selector(reFreshHelper.onRefresh), for: .valueChanged)
            scrollview.refreshControl = control
        }
    }

    final class RefreshHelper {
        var parent: CustomScrollView?
        var refreshControl: UIRefreshControl?

        @objc func onRefresh(){
            self.refreshControl?.beginRefreshing()
            self.parent?.refreshable()
            self.refreshControl?.endRefreshing()
        }
    }
}

```

https://user-images.githubusercontent.com/51524705/210739126-523fbf45-41a6-4529-a695-bf376a96725f.mp4

**Comment by Mercen-Lee** [comment]
Same Issue

**Comment by Mercen-Lee** [comment]
Same issue

**Comment by hoangnam714** [comment]
@Mercen-Lee I have temporarily fixed this bug by checking iOS version, please use refreshable on iOS >16 and above and introspect on iOS < 16 then you won't get the above bug

**Comment by Mercen-Lee** [comment]
> @Mercen-Lee I have temporarily fixed this bug by checking iOS version, please use refreshable on iOS >16 and above and introspect on iOS < 16 then you won't get the above bug

Thanks for your help. But I've already switched to the library named Refresher.

**Comment by hoangnam714** [comment]
@Mercen-Lee I used that library, it's very bad, there is a bug when pulling to refresh on iOS 16

**Comment by Mercen-Lee** [comment]
> @Mercen-Lee I used that library, it's very bad, there is a bug when pulling to refresh on iOS 14 and iOS 15

Whoa, I didn't know that. Nice feedback. Thank you :)

**Comment by davdroman** [comment]
This isn't really a bug in this introspection library, more of a bug in the underlying SwiftUI/UIKit implementation of ScrollView/UIScrollView by Apple. Hopefully most people can adopt refreshable at this point, but for those who can't there are other ready-made libraries out there that accomplish this.

Closing for now.

**Comment by keremcesme** [comment]
Hi @davdroman , I am trying to implement your solution by creating `.onRefresh(action:)` ViewModifier. 

The task in `onRefresh(action:)` is never executed. Also, the `UIRefreshControll` never ends and constantly runs on the screen. I don't know if there is something I missed. 
    
    import SwiftUI
    import SwiftUIIntrospect
    
    struct ScrollViewRefreshableModifier: ViewModifier {
        private let coordinator: Coordinator
        
        init(_ action: @escaping () async -> Void) {
            self.coordinator = Coordinator(action)
        }
        
        func body(content: Content) -> some View {
            content
                .introspect(.scrollView, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { scrollView in
                    guard scrollView.refreshControl == nil else {
                        return // Avoids repetitive work. Unrelated to solution, just good etiquette.
                    }
                    let control = UIRefreshControl()
                    control.addTarget(coordinator, action: #selector(coordinator.pullToRefreshStarted), for: .valueChanged)
                    coordinator.refreshControl = control
                    scrollView.refreshControl = control
                }
        }
        
        final class Coordinator {
            private var action: () async -> Void
            weak var refreshControl: UIRefreshControl?
            
            init(_ action: @escaping () async -> Void) {
                self.action = action
            }
            
            @objc func pullToRefreshStarted() {
                self.refreshControl?.beginRefreshing()
                Task { @MainActor [weak self] in
                    await self?.action()
                    try await Task.sleep(nanoseconds: 0) // forces a main thread skip in case refresh finishes instantly
                    self?.refreshControl?.endRefreshing()
                }
            }
        }
    }

    extension View {
        public func onRefresh(_ action: @escaping () async -> Void) -> some View {
            modifier(ScrollViewRefreshableModifier(action))
        }
    }

Usage on `ScrollView`:

    ScrollView { ... }
        .onRefresh {
            print("REFRESHING") // never execute
        }

**EDIT**: In addition, after editing the code this way, it started to work without any problems. The code works like this, but I'm unsure if it's a good solution.

    struct ScrollViewRefreshableModifier: ViewModifier {
        private var action: () async -> Void
        private var refreshControl = UIRefreshControl()
        
        public init(_ action: @escaping () async -> Void) {
            self.action = action
        }
        
        private var refresh: UIAction {
            return .init { _ in Task { @MainActor [self] in
                    await self.action()
                    refreshControl.endRefreshing()
                }
            }
        }
        
        func body(content: Content) -> some View {
            content
                .introspect(.scrollView, on: .iOS(.v13, .v14, .v15, .v16, .v17), customize: scrollView)
        }
        
        private func scrollView(_ scrollView: UIScrollView) {
            guard scrollView.refreshControl == nil else { return }
            refreshControl.addAction(refresh, for: .valueChanged)
            scrollView.refreshControl = refreshControl
        }
    }

    extension View {
        public func onRefresh(_ action: @escaping () async -> Void) -> some View {
            modifier(ScrollViewRefreshableModifier(action))
        }
    }

After edit:

    ScrollView { ... }
        .onRefresh {
            print("REFRESHING") // execute
            try? await Task.sleep(seconds: 3) //  Refresh Control disappears after 3 seconds.
        }

**Comment by davdroman** [comment]
@keremcesme nothing wrong with your solution. Just bear in mind [`addAction(_:for:)`](https://developer.apple.com/documentation/uikit/uicontrol/3600490-addaction) is only available on iOS 14 and later. Not a problem if you don't need iOS 13 support.
