### ISSUE TITLE
Could not find module 'Introspect' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by ColtonIdle** [siteline/SwiftUI-Introspect#189]
> Could not find module 'Introspect' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: 
> /Users/cidle/Library/Developer/Xcode/DerivedData/RollerToaster-asdf/Index.noindex/Build/Products/Debug-
> iphonesimulator/Introspect/Introspect.framework/Modules/Introspect.swiftmodule

Trying to run a project on a sim and getting the error above. Is introspect not compat with m1?

**Comment by davdroman** [comment]
Introspect is fully M1 compatible. I maintain it from my M1 machine.

Are you using SPM? If so, would you mind pointing to the `master` branch and trying again? If that doesn't work either, try a Clean Build Folder or even delete Derived Data as sometimes Xcode gets confused about valid package architectures.

**Comment by ColtonIdle** [comment]
not using spm.
deleted derivced data and cleaned. no dice. hm.

let me know if you have any other thoughts, but thanks for confirming that it should indeed work. its my first day on a new project and im justt trying to figure out why Introspect is being complained about.

**Comment by davdroman** [comment]
@ColtonIdle fair enough. So I assume your team is using CocoaPods then? I'm a bit out of my depth on CocoaPods as I haven't used it in years, but I'll investigate this on my side with my M1 machine and come back to you if I can repro.

**Comment by ColtonIdle** [comment]
@davdroman thank you! Yeah, cocoapods. i can deploy to my device fine. just launching in the sim is apparently the issue

**Comment by SplittyDev** [comment]
@ColtonIdle we don't have access to CocoaPods, so it's likely that quite a few more recent bugfixes aren't available via CocoaPods yet. @davdroman maybe after releasing the new version you could ping Loïs to make a CocoaPods release?

**Comment by davdroman** [comment]
@SplittyDev yup, I just tagged a new version [0.2.0] and will send an email out to request a push to CocoaPods trunk shortly.

**Comment by davdroman** [comment]
Hi @ColtonIdle! 0.2.2 is now available via CocoaPods. Please update your branch and let me know if your issue is fixed :)

**Comment by lemonjuicer** [comment]
Could not find module 'Introspect' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, Still exists for Swift packages

**Comment by davdroman** [comment]
@lemonjuicer perhaps @ColtonIdle was able to fix it somehow and can share some more details?

This sounds to me like there might be a misconfiguration in your Xcode project, perhaps look at architecture build settings? Hard to say without a reproducible example.

**Comment by lemonjuicer** [comment]
I am still poking around - keep the thread posted if I find a solution :)

**Comment by lemonjuicer** [comment]
This is for anyone who is still having this problem: 
The fix for me was to ditch SPM entirely and just migrate all my dependencies to Cocoapods. Clean the project and deintegrate any existing pods and just re pod install and done.

**Comment by ColtonIdle** [comment]
i wasn't able to fix my issue unfortunately. let me know if you find a solution

**Comment by davdroman** [comment]
With the release of the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module this issue is now outdated. I'm hoping the same issue doesn't happen with it, but if it does feel free to reopen and we can continue the discussion.

**Comment by davdroman** [comment]
[Some more light](https://github.com/siteline/SwiftUI-Introspect/issues/336#issuecomment-1689619271) has been shed on this issue thanks to @oscarkockum:

> Had an EXCLUDED_ARCHS arm64 due to an old GoogleMaps SDK workaround. Removing it fixed the issue.

Hopefully this helps anybody still struggling with this.

**Comment by ColtonIdle** [comment]
i use gmaps too. ill check this out. thanks @davdroman
