### ISSUE TITLE
Regression: UIKitIntrospectionViewController doesn't handle state updates

### ISSUE THREAD

**Issue by chwo** [siteline/SwiftUI-Introspect#194]
### Description
- The behaviour of the `UIKitIntrospectionViewController` was changed in version 0.2.0 https://github.com/siteline/SwiftUI-Introspect/pull/165
- Previously (version 0.1.4), the `customize` handler was called in the `updateUIViewController` so it was called on state changes
- Now, the `customize` handler is only called in `makeUIViewController` so it is only called with the initial state and isn't called on state changes

### Use case
We use `introspectSearchController` to introspect a SwiftUI List with the `searchable` modifier and want to configure properties of the searchController based on the state (if the list is empty or not). So the `customize` handler needs to be called again if the state (the list entries) changes.

**Comment by davdroman** [comment]
Great point. Okay so the fix should be to call the customize callback in `updateViewController` also. Will make a PR shortly.

**Comment by davdroman** [comment]
@chwo this is now fixed in 0.2.1. Please update and let me know if it works for you.

**Comment by davdroman** [comment]
I can confirm #192 didn't fix this for some reason. I'm currently investigating why.

**Comment by davdroman** [comment]
This is now actually fixed in 0.2.2, I tested it with [one of my libraries](https://github.com/davdroman/swiftui-navigation-transitions) which broke with 0.2.0. Closing for now but feel free to reopen if you experience this issue again.

**Comment by chwo** [comment]
@davdroman I have tested it and it works again in 0.2.2. Thank you for the fast fix. 🙌
