### ISSUE TITLE
Textfield breaks the typing and flashes when use textField.becomeFirstResponder() in language other than English.

### ISSUE THREAD

**Issue by legolasW** [siteline/SwiftUI-Introspect#20]
It works great for English. However, it refreshes every single type for other languages that requires user to select a word from keyboard. For example, in Chinese, the word picker flash every time you type a new character. Could you please check what went wrong? Thanks

**Comment by legolasW** [comment]
https://youtu.be/ngExUJ7gyb8

**Comment by legolasW** [comment]
`            TextField("Tap here", text: $inputText)
                .padding()
                .introspectTextField { textField in
                    textField.becomeFirstResponder()
            }`

**Comment by SplittyDev** [comment]
@legolasW are you still experiencing this issue?

We've just tested this on `master` branch (macOS 11 and iOS 14).
Seems to work fine for Chinese (Simplified) and other languages.

**Comment by legolasW** [comment]
Thank you for the update!

Works good after iOS 14.3
It seems like a bug on SwiftUI 1.0 and appears to be fixed:D

**Comment by SplittyDev** [comment]
@legolasW thanks a lot for the quick reply!

We'll close the issue then, feel free to open another one if you experience any other bugs :)
