### ISSUE TITLE
introspectTableView dosen't work

### ISSUE THREAD

**Issue by JPSaber** [siteline/SwiftUI-Introspect#211]
block callbacks are not executed after the introspectTableView and introspectTableViewCell methods are called, on iOS16.0 or above
`.introspectTableView(customize: { tableView in
            Log("tableView")
        })
        .introspectTableViewCell(customize: { cell in
            Log("cell")
        })`

**Comment by davdroman** [comment]
Please see https://github.com/siteline/SwiftUI-Introspect/issues/175
