### ISSUE TITLE
Failed in submission to App Store. 

### ISSUE THREAD

**Issue by legolasW** [siteline/SwiftUI-Introspect#22]
<img width="1092" alt="Screen Shot 2020-03-29 at 6 58 35 AM" src="https://user-images.githubusercontent.com/41680926/77851140-3d897480-718c-11ea-8453-6df42a2e045b.png">

**Comment by ldiqual** [comment]
@legolasW Thanks for filing an issue! How are you integrating the library? Cocoapods / SwiftPM / other?

**Comment by ldiqual** [comment]
Closing due to the lack of activity. Please feel free to comment and I'll reopen.
