### ISSUE TITLE
An Amazing Implementation. Hats off! Though I have a question!

### ISSUE THREAD

**Issue by anupamchugh** [siteline/SwiftUI-Introspect#24]
Essentially, the library adds a duplicate overlay view in order to access the underlying view. Right? 
I'm planning to use this library in one of blogs.

**Comment by ldiqual** [comment]
That's correct. Introspect adds a 0pt x 0pt overlay onto the target, which means it's alongside the target in the view hierarchy. Please let me know if you have any other question, in the meantime I'll close this issue. Thank you!

**Comment by jevonmao** [comment]
@ldiqual I am having some trouble grasping the concept of Introspect "looking" through the hierarchy to get the UIKit view. Why is it necessary to add a 0pt x 0pt overlay onto the target? What's the purpose? I don't understand how injecting a custom `IntrospectionView` is required. A quick lesson on how Introspect work under the hood is appreciated. Thank you.
