### ISSUE TITLE
TextField focus does not work with .fullScreenCover.

### ISSUE THREAD

**Issue by goors** [siteline/SwiftUI-Introspect#248]
```
.fullScreenCover(isPresented: self.$loginToAccount) {
    TextField("Email", text: self.$email)
    .introspectTextView { email in
         email.becomeFirstResponder()            
    }
}
```

If you put in break point at` introspectTextView` nothing is happening.

**Comment by davdroman** [comment]
@goors I assume you probably found the reason it's not working (`.introspectTextField`), but regardless I'd suggest using the [new `SwiftUIIntrospect` module](https://github.com/siteline/SwiftUI-Introspect/blob/master/docs/SwiftUIIntrospect.md) instead:

```swift
.fullScreenCover(isPresented: self.$loginToAccount) {
    TextField("Email", text: self.$email)
		.introspect(.textField, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { email in
			email.becomeFirstResponder()
		}
}
```
