### ISSUE TITLE
Unable to import SwiftUIIntrospect (0.7.0)

### ISSUE THREAD

**Issue by nebsta** [siteline/SwiftUI-Introspect#283]
<img width="1116" alt="Screenshot 2023-06-29 at 15 09 34" src="https://github.com/siteline/SwiftUI-Introspect/assets/94231771/d3dfd40c-99a1-4ae5-aa93-c5767c89aa23">

I recently tried upgrading to version 0.7.0, and saw the deprecating warnings for the old `Introspect` module, however when I try to import `SwiftUIIntrospect` instead XCode complains that the module doesn't exist. 

My machine is currently running Swift 5.8.1, and our Swift Compiler Language for the project is set to 5 on XCode version 14.3.1, so I would assume it should be using the minimum 5.7 required. Is there something else I'm missing here?

**Comment by davdroman** [comment]
Hi @nebsta, thanks for the detailed report. It could be you might’ve forgotten to link the module against your app/SPM target. `SwiftUIIntrospect` is a different module from `Introspect` so it must be linked in order for it to be imported.

Let me know how it goes.

**Comment by nebsta** [comment]
@davdroman derp, I knew it was probably something obvious -_-;. Thanks for resolving my dumb problem!
