### ISSUE TITLE
Get UIViewController in v0.7.0

### ISSUE THREAD

**Issue by honkmaster** [siteline/SwiftUI-Introspect#286]
Is there an equivalent to the func introspectViewController planned in the upcoming release?

**Comment by davdroman** [comment]
I wasn’t planning on it, but if it’s helpful I will. Can you tell me more about how it’s useful in your case?

**Comment by honkmaster** [comment]
In the current version I am using the access to the  `UIViewController` to 
- access the `sheetPresentationController` and modify `prefersGrabberVisible`, and
- modify `hidesBottomBarWhenPushed` as there is a Bug and toolbar(.hidden) is only available in iOS 16+

**Comment by davdroman** [comment]
Cool, thanks for the explanation. You can definitely add your own extension, but the goal is for the library to contain as many core components as possible so consumers don't need to implement much themselves.

For the `sheetPresentationController ` use case, you can now do:

```swift
public struct ContentView: View {
    @State var isPresented = false

    public var body: some View {
        Button("Present", action: { isPresented = true })
            .sheet(isPresented: $isPresented) {
                Button("Dismiss", action: { isPresented = false })
                    .introspect(.sheet, on: .iOS(.v15, .v16, .v17)) { (controller: UISheetPresentationController) in
                        controller.prefersGrabberVisible = true
                    }
            }
    }
}
```

As for the `hidesBottomBarWhenPushed` bit, I was under the impression that changing that property [has never really worked](https://github.com/siteline/SwiftUI-Introspect/issues/137). I'll take it for a spin and see if that's different now with this new module.

**Comment by michzio** [comment]
> In the current version I am using the access to the `UIViewController` to
> 
> * access the `sheetPresentationController` and modify `prefersGrabberVisible`, and
> * modify `hidesBottomBarWhenPushed` as there is a Bug and toolbar(.hidden) is only available in iOS 16+
> 
> But, as I read the documentation, I can add my own extension, right?
> 
> ```
> @_spi(Internals) import SwiftUIIntrospect
> import UIKit
> 
> public struct ViewControllerType: IntrospectableViewType {}
> 
> public extension IntrospectableViewType where Self == ViewControllerType {
>     static var viewController: Self { .init() }
> }
> 
> #if canImport(UIKit)
>     public extension iOSViewVersion<ViewControllerType, UIViewController> {
>         static let v15 = Self(for: .v15)
>         static let v16 = Self(for: .v16)
>     }
> #endif
> ```

It needs to be @_spi(Advanced)

**Comment by davdroman** [comment]
@michzio 

> But for me your extension doesn't work in predicatable way.

That's because you need to override the default `scope` for the view, as you're looking up the ancestor tree, not down the receiver.

Try this:

```swift
import SwiftUI
@_spi(Advanced) import SwiftUIIntrospect

public struct ViewControllerType: IntrospectableViewType {
    public var scope: IntrospectionScope { .ancestor }
}

extension IntrospectableViewType where Self == ViewControllerType {
    public static var viewController: Self { .init() }
}

#if canImport(UIKit)
extension iOSViewVersion<ViewControllerType, UIViewController> {
    public static let v13 = Self(for: .v13)
    public static let v14 = Self(for: .v14)
    public static let v15 = Self(for: .v15)
    public static let v16 = Self(for: .v16)
    public static let v17 = Self(for: .v17)
}

extension tvOSViewVersion<ViewControllerType, UIViewController> {
    public static let v13 = Self(for: .v13)
    public static let v14 = Self(for: .v14)
    public static let v15 = Self(for: .v15)
    public static let v16 = Self(for: .v16)
    public static let v17 = Self(for: .v17)
}
#endif
```

**Comment by davdroman** [comment]
@honkmaster this is now implemented in master and will be part of the next release (0.9.0).
