### ISSUE TITLE
Would like support for MKMapView

### ISSUE THREAD

**Issue by vectorstofinal** [siteline/SwiftUI-Introspect#287]
Tried adding it like this but keep getting this error:

_**Static property 'map' requires the types 'ColorPickerType' and 'MapKitType' be equivalent**_

`@_spi(Internals) import SwiftUIIntrospect

public struct MapKitType: IntrospectableViewType {}

extension IntrospectableViewType where Self == MapKitType {
    public static var map: Self { .init() }
}

#if canImport(UIKit)
extension iOSViewVersion<MapKitType, MKMapView> {
    public static let v13 = Self(for: .v13)
    public static let v14 = Self(for: .v14)
    public static let v15 = Self(for: .v15)
    public static let v16 = Self(for: .v16)
}

extension tvOSViewVersion<MapKitType, MKMapView> {
    public static let v13 = Self(for: .v13)
    public static let v14 = Self(for: .v14)
    public static let v15 = Self(for: .v15)
    public static let v16 = Self(for: .v16)
}
#elseif canImport(AppKit)
extension macOSViewVersion<MapKitType, MKMapView> {
    public static let v10_15 = Self(for: .v10_15)
    public static let v11 = Self(for: .v11)
    public static let v12 = Self(for: .v12)
    public static let v13 = Self(for: .v13)
}
#endif`

**Comment by davdroman** [comment]
Can you post an extract of the call site where this code is used, where the error appears?

Either way it’s a good shout to add support for map introspection so I’ll do that over the weekend 👍

**Comment by vectorstofinal** [comment]
Thanks!
My "caller" code is (error is on the .introspect line):

```
Map( coordinateRegion: $region, annotationItems: locations){ loc in
            
        }
        .introspect(.map, on: .iOS(.v16, .v17) ){ mapView in
}
```

**Comment by davdroman** [comment]
Ah, I think it’s cause you’re missing a v17 declaration in your extension :)

**Comment by vectorstofinal** [comment]
You're exactly right, gotta love a clear compiler error :)

FWIW, I was stealing that code from the README (towards the end) https://github.com/siteline/SwiftUI-Introspect

**Comment by davdroman** [comment]
Yeah, this library pushes the compiler to its very limit 😄 

Thanks for the heads up, will update that too this weekend, or feel free to submit a PR if you fancy.

**Comment by vectorstofinal** [comment]
The new update seems to work well, thanks so much!!!
