### ISSUE TITLE
textField.becomeFirstResponder() is reason for bad transition

### ISSUE THREAD

**Issue by KonstantinEfimenko** [siteline/SwiftUI-Introspect#30]
When I use 

     `TextField("onboarding_name_firstname".localized, text: $state.firstName)
                .textFieldStyle(TextFields(.bordered))
                .disableAutocorrection(true)
                .accessibility(identifier: "onboarding_name_firstname")
                .introspectTextField(customize: { textField in
                    textField.becomeFirstResponder()
                })`

on opening this screen it looks like screen was opened twice: one without keyboard, the second with.
Commenting string textField.becomeFirstResponder() helps with such transition but off course keyboard is closed

**Comment by Michaelsafir** [comment]
_BSMachError: port 15103; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
_BSMachError: port 8a03; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

Yep, same problem - open twice 

 .introspectTextField { (textfield) in
                                print("hello")
                                textfield.becomeFirstResponder()
                        }

**Comment by DonSwet** [comment]
Possible workaround: Change value the transition responds to using withAnimation(myAnimation) { variable = newValue }

**Comment by malhal** [comment]
becomeFirstResponder is a method, not a property you would want to customise every time the view is updated.

**Comment by amkomatz-ggd** [comment]
Any update on this? I am also having this problem

**Comment by aaronLab** [comment]
Same here :(

**Comment by grenos** [comment]
same

**Comment by grenos** [comment]
TextField("test", text: $test)
		.textFieldStyle(RoundedBorderTextFieldStyle())
		.keyboardType(.phonePad)
		.introspectTextField { textField in
			DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
				textField.becomeFirstResponder()
				textField.textContentType = .oneTimeCode
			}
		}


It seems that the problem occurs when the transition animation of the navigation hasn't finished yet. Delaying the keyboard animation for half a second seems to work but I'm not sure is the ideal solution.

**Comment by JannThomas** [comment]
Hi, as long as the `. introspectTextField()` function does work and returns the right `UITextField`, this issue is not in the scope of this project. That said I will close this issue now.
