### ISSUE TITLE
Introspect textField leads to undefined beh

### ISSUE THREAD

**Issue by Jameszjwchang** [siteline/SwiftUI-Introspect#302]
Hello!

When I tried to run the app after implementing the Introspect textField modifier, an issue comes up saying that this will cause undefined behavior in the view: ```Modifying state during view update, this will cause undefined behavior.```
I am not sure what is the issue here. Is this a bug in the swiftUI-Introspect module?

This is the code snippet that I used:
```
.introspect(.textField, on: .iOS(.v16, .v17)) { UITextField in
    UITextField.becomeFirstResponder()
}
```

I have previously used this code from the original Introspect module to apply the becomeFirstResponder modifier to a textField, and it is working fine:
```
.introspectTextField(customize: { UITextField in
    UITextField.becomeFirstResponder()
})
```
But the only issue is that this module will be depreciated soon. Could this be looked into? Thanks in advance.

**Comment by davdroman** [comment]
Here's how to do it:

```swift
.introspect(.textField, on: .iOS(.v16, .v17)) { textField in
    DispatchQueue.main.async {
        textField.becomeFirstResponder()
    }
}
```

### Explanation

The old `Introspect` implementation always performed a thread hop for the introspection callback. The new `SwiftUIIntrospect` implementation is more refined and performs the callback as soon as possible without needing to thread hop at all, which is beneficial in most cases except when you need to perform state mutations right away — such as this one.

**Comment by Jameszjwchang** [comment]
Thanks for providing a solution for the problem above! There is another issue, though:

https://github.com/siteline/SwiftUI-Introspect/assets/120231221/cc2b4a63-5407-497a-bb7e-211b38b26c6c

As shown in the screen recording, the keyboard "lags behind" for a short duration even after the sheet has been closed. I am also not sure what the issue is here.

**Comment by davdroman** [comment]
That doesn’t seem related to introspection, unless removing the `.introspect` call fixes the issue somehow.

**Comment by Jameszjwchang** [comment]
I found the issue; there was apparently something weird about the way that iOS 17 beta 3 was handling textfields, and this bug happened to be one of them. I tested this again on a simulator and this issue did not appear.
