### ISSUE TITLE
How to use Introspect in backwards compatible projects

### ISSUE THREAD

**Issue by Amzd** [siteline/SwiftUI-Introspect#31]
I have an app that supports iOS 11 and up but we're transferring parts of it to SwiftUI. I want to use Introspect but cocoapods complains about Introspect's iOS 13 deployment target.

Is there a simple way to fix this?

I'm pretty sure SwiftUI adds backwards compatibility by adding `@available(iOS 13.0, OSX 10.15, tvOS 13.0, watchOS 6.0, *)` to it's public types.

**Comment by ldiqual** [comment]
Support for older OS versions was added in https://github.com/siteline/SwiftUI-Introspect/pull/28. You can use the master branch with Cocoapods/SwiftPM until we release it. Thank you!
