### ISSUE TITLE
.introspectTabBarController { }  does not exist in the SwiftUIIntrospect

### ISSUE THREAD

**Issue by madazaharia** [siteline/SwiftUI-Introspect#310]
Hello,

I tried to migrate from 0.3.1 -> 0.9.1 and I did not find the equivalent to the ".introspectTabBarController" type.
I need to read the height of the tabBar:

. introspectTabBarController { tabBarController in
      tabBarHeight = tabBarController.tabBar.bounds.size.height
}

I need your help.
Thank you!

**Comment by davdroman** [comment]
You want to introspect `TabView`, so:

```swift
TabView {
	...
}
.introspect(.tabView, on: .iOS(.v13, .v14, .v15, .v16, .v17)) { tabBarController in
	tabBarHeight = tabBarController.tabBar.bounds.size.height
}
```

**Comment by hchopra-godaddy** [comment]
Can we hide tabBar from `TabView` using this?

And if a view have two `TabView`s one at root and other at Chile level then which one `.introspect` will find?
