### ISSUE TITLE
Status bar style gets reset on pop

### ISSUE THREAD

**Issue by VladOrackle** [siteline/SwiftUI-Introspect#311]
In our app we use UIKit Navigation + SwiftUI views wrapped inside UIHostingController
For some screens we need to override default status bar style by means of changing it inside UIHostingController instance

Using new SwiftUIIntrospect on some of the subviews makes status bar lose its style on popping from previous screens. Removing introspection resolves the issue.

Minimal example attached 

[IntrospectBug.zip](https://github.com/siteline/SwiftUI-Introspect/files/12049513/IntrospectBug.zip)

https://github.com/siteline/SwiftUI-Introspect/assets/61315957/4d7250a2-419a-46ac-b085-63485a175d77

**Comment by davdroman** [comment]
Thanks for the exhaustive report, I'll look into it as soon as I can and get back to you.

**Comment by davdroman** [comment]
@VladOrackle thanks for your patience. I was able to come up with a fix in #313. Before I merge it, I'd appreciate if you could confirm it works for you too by pointing to the branch `fix-wrong-status-bar-style`. Cheers.

**Comment by VladOrackle** [comment]
@davdroman 
It does work, but only sometimes.
In my minimal example I introspected **viewController**, but if we change it to some other component, **scrollView** for example, the fix strangely stops working

Updated example attached
[IntrospectBug.zip](https://github.com/siteline/SwiftUI-Introspect/files/12082104/IntrospectBug.zip)

**Comment by davdroman** [comment]
Oh right I see, it goes deeper than I thought then. I'll keep digging. Thanks for the heads up!

**Comment by VladOrackle** [comment]
@davdroman forgot to mention that on iOS 15 & 17 it does work as it should without any changes. The problem seems to affect only iOS 16 as you mentioned before

**Comment by davdroman** [comment]
@VladOrackle cool, good to confirm. I think I found the solution for all view types, if you point to the latest commit (b220886) in the branch and check I'd appreciate it.

**Comment by VladOrackle** [comment]
> @VladOrackle cool, good to confirm. I think I found the solution for all view types, if you point to the latest commit ([b220886](https://github.com/siteline/SwiftUI-Introspect/commit/b2208865caa4e7cc4064893bfbdbb98c4ac0c7b3)) in the branch and check I'd appreciate it.

Checked, and it works perfectly! Many thanks

**Comment by davdroman** [comment]
Excellent! I'll write a UI test, merge, and tag a release shortly.
