### ISSUE TITLE
no such file no such file or directory: Introspect-Dynamic.framework/Introspect-Dynamic

### ISSUE THREAD

**Issue by staticdreams** [siteline/SwiftUI-Introspect#318]
I'm having trouble compiling application for device.
This is the exact 2 issues I'm having:

    clang: no such file or directory: '/Users/peter/Library/Developer/Xcode/DerivedData/Cinepub- 
    brqgtlkhcrcgxahldoskfqsuoqid/Build/Products/Debug-iphoneos/PackageFrameworks/Introspect-Dynamic.framework/Introspect- 
    Dynamic'

    clang: error: no such file or directory: '/Users/peter/Library/Developer/Xcode/DerivedData/Cinepub- 
    brqgtlkhcrcgxahldoskfqsuoqid/Build/Products/Debug-iphoneos/PackageFrameworks/SwiftUIIntrospect- 
    Dynamic.framework/SwiftUIIntrospect-Dynamic'``

And if inside ``SwiftUIIntrospect-Dynamic.framework`` it confirms it: no such file SwiftUIIntrospect-Dynamic or Introspect- 
    Dynamic

Simulator run the application without any issues.

FYI I'm using latest Xcode 15 beta 4, running iOS 17 simulator

My device is iPhone 14 Pro iOS 16.5.1

SwiftUI-introspect: 0.9.4

**Comment by davdroman** [comment]
Okay I think I might've narrowed it down to this needing to be checked:

<img width="996" alt="image" src="https://github.com/siteline/SwiftUI-Introspect/assets/2538074/9c23fd29-5cda-4734-bf45-373ddbf00900">

**Comment by davdroman** [comment]
Also as a tip, unless you really need the dynamic version of the module it's probably best to just use `SwiftUIIntrospect` and let SPM figure out the linking mode for you.

**Comment by DuncanMC** [comment]
> Thanks for the tip @davdroman ! The dynamic version was already Embed & Signed. However, everything worked when I got rid of dynamic and static versions, leaving just Introspect.

@staticdreams how did you "[get] rid of dynamic and static versions? Did you update introspect's Package.swift file and comment out the `.libary()` declarations for the static and dynamic versions, or something else?

**Comment by staticdreams** [comment]
@DuncanMC If I recall correctly, it is during the package installation it asks you what do you want to include. Like main library, dynamic and static. I just unchecked everything a part from the main one.
