### ISSUE TITLE
Can't use Introspect on macCatalyst Projects

### ISSUE THREAD

**Issue by Ash-Bash** [siteline/SwiftUI-Introspect#33]
Can't use Introspect on macCatalyst Projects, it thinks im running a full blown AppKit Project instead of UIKit running on Mac.

**Comment by orospakr** [comment]
Hey @Ash-Bash this is a known issue, a regression in the most recent release, and a fix is in master (I think), but a release hasn't been done. Either go to the penultimate release 0.0.6, or try master.

**Comment by PedroCavaleiro** [comment]
Using master works just fine on my project @Ash-Bash

**Comment by JannThomas** [comment]
I will close this issue since it works in the newest release.
