### ISSUE TITLE
Xcode15 compile error

### ISSUE THREAD

**Issue by whuxujiyuan** [siteline/SwiftUI-Introspect#336]
<img width="704" alt="image" src="https://github.com/siteline/SwiftUI-Introspect/assets/1314078/4a91e8b4-9b9c-4085-ba3e-c52f11a92a7f">

**Comment by davdroman** [comment]
That looks like a very old version. Update to the latest version of SwiftUIIntrospect (0.11.0) and let me know if it works.

**Comment by oscarkockum** [comment]
I have the same issue when installing using Cocoapods. When I install using SPM I get 
Could not find module for target 'x86_64-apple-ios-simulator'... (works building on device but need simulator for SwiftUI previews)



M1
Xcode 15 Beta 6

**Comment by oscarkockum** [comment]
Hi @davdroman !

I created a quick project but could not reproduce the error, and found out the issue comparing the build settings.
Had an EXCLUDED_ARCHS arm64 due to an old GoogleMaps SDK workaround. Removing it fixed the issue.

**Comment by davdroman** [comment]
@oscarkockum that's excellent news! I'll cross post this to #189 to help folks still struggling with this.

**Comment by davdroman** [comment]
@oscarkockum just to clarify, is this particular `Protocol requirement ... cannot be declared '@_spi' ...` issue fixed as well, or just the `x86_64-apple-ios-simulator` one?

**Comment by whuxujiyuan** [comment]
- using pod
- Intel
- Xcode 15 beta 6(the latest)
- please see attachment
- [Demo.zip](https://github.com/siteline/SwiftUI-Introspect/files/12426048/Demo.zip)

**Comment by whuxujiyuan** [comment]
xcode15 beta7 is the same error

**Comment by davdroman** [comment]
@whuxujiyuan so it seems it's this line in your Podfile that's causing the issue:

```
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
```

Now, I don't know exactly why that flag is set. I'd appreciate some more insight on that. But as far as the error goes, I should be able to work out a fix by adding a default conformance as suggested.
