### ISSUE TITLE
PartialLowerBound overload for platform versions doesn't compile

### ISSUE THREAD

**Issue by theoks** [siteline/swiftui-introspect#354]
### Description

I am trying to use the `PartialLowerBound` overload to define the platform versions for introspection like this:

```
.introspect(.textEditor, on: .iOS(.v15...)) { view in
    view.backgroundColor = .clear
}
```

instead of the variadic version:

```
.introspect(.textEditor, on: .iOS(.v15, .v16, .v17)) { view in
    view.backgroundColor = .clear
}
```

however I get the following compilation error with the first alternative:

> Cannot convert value of type '()' to expected argument type 'PlatformViewVersion<iOSVersion, TextEditorType, PlatformSpecificEntity>'

The second alternative works as expected.

Am I using a wrong syntax in the first case or there is indeed a compilation issue?

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Version information

0.12.0

### Destination operating system

iOS 16

### Xcode version information

14.3.1 (14E300c)

### Swift Compiler version information

```shell
1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
```

**Comment by davdroman** [comment]
My first hunch is you need to make sure to use the following import statement:

```swift
@_spi(Advanced) import SwiftUIIntrospect
```

**Comment by davdroman** [comment]
Based on my response's reaction that seems to be solution, so I'll close this now.

**Comment by theoks** [comment]
@davdroman that did the trick, thanks!
