### ISSUE TITLE
Introspection not working for SwiftUI advances in iOS 14

### ISSUE THREAD

**Issue by jtouzy** [siteline/SwiftUI-Introspect#37]
I recently use introspection to add a toolbar on top of keyboard on some textfields (and also to manage first responder).
I just tried on Xcode 12 Beta 1, with iOS 14 device, it's not working anymore, nothing is added.

With this basic usage via a ViewModifier :

```swift
struct KeyboardToolbar: ViewModifier {
    private let toolbarCoordinator = ToolbarCoordinator()
    var actions: [KeyboardToolbarAction]

    init(actions: [KeyboardToolbarAction]) {
        self.actions = actions
    }

    func body(content: Content) -> some View {
        content.introspectTextField {
            self.buildToolbar(on: $0)
        }
    }

    private func buildToolbar(on textField: UITextField) {
        guard textField.inputAccessoryView == nil else { return }
        let customToolbar = UIToolbar()
        customToolbar.items = toolbarCoordinator.createBarButtonItems(on: textField, actions: actions)
        customToolbar.sizeToFit()
        textField.inputAccessoryView = customToolbar
    }
}
```

The introspectTextField handler is never called. I suspect the view hierarchy has changed in iOS 14.
To give you a quick snap of the view hierarchy in iOS 14 :

![Screenshot 2020-06-24 at 16 04 47](https://user-images.githubusercontent.com/5709133/85571578-8c806200-b634-11ea-9084-d3e2b4524309.png)

**Comment by gianfrangiamore** [comment]
I'm not sure this is issue is limited to Introspect. If you try adding system wide styling using `UITableView.appearance()` it doesn't work.

It would seem something is broken in the current beta.

**Comment by rushairer** [comment]
I'm having same issue. I'm using macOS 11.6 beta, Xcode 12 beta.

**Comment by JannThomas** [comment]
@jtouzy @rushairer Can you confirm this still happens on the newest master? We fixed some issues with text fields in a recent PR.

If this still happens please attach a view hierarchy in which it does.

**Comment by JannThomas** [comment]
As you have not replied within a week I will close this issue for now. Please reopen it if you still experience this issue.
