### ISSUE TITLE
Unable to use ranges (.v15...)

### ISSUE THREAD

**Issue by aehlke** [siteline/swiftui-introspect#384]
### Description

<img width="524" alt="image" src="https://github.com/siteline/swiftui-introspect/assets/71601/c49601e2-df0f-45e6-a89c-10c642724532">

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

**Comment by davdroman** [comment]
See https://github.com/siteline/swiftui-introspect/issues/354#issuecomment-1712177770.
