### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MiaShopgal** [siteline/swiftui-introspect#387]
### Description

It's working on a simulator, but when changing to a device, there's a build error.

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Expected behavior

can run on a device

### Actual behavior

build error :
no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/SwiftUIIntrospect-dedgxvczfmevyagrtjzlvhjnlbge/Build/Products/Debug/PackageFrameworks/SwiftUIIntrospect-Dynamic.framework/Versions/A/SwiftUIIntrospect-Dynamic'

### Steps to reproduce

clone repo
open SwiftUIIntrospect.xcworkspace with Xcode
build / run Showcase on a device

error occurs

### Version information

SwiftUIIntrospect 1.1.1

### Destination operating system

iPhone X / iPhone SE 2nd / My Mac

### Xcode version information

15.0.1

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

**Comment by nazar-41** [comment]
same issue

**Comment by davdroman** [comment]
See https://github.com/siteline/swiftui-introspect/issues/318
