### ISSUE TITLE
App hangs when introspect framework linked to

### ISSUE THREAD

**Issue by wtmoose** [siteline/swiftui-introspect#400]
### Description

The mere linking to the Introspect framework, without even importing the framework, causes an app to hang under certain conditions. In particular, when pushing a view onto a navigation stack when other specific conditions exist (see attached minimal sample app).

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Expected behavior

App pushes a view onto the navigation stack

### Actual behavior

App hangs with 100% CPU

### Steps to reproduce

1. Run the attached minimal sample app
2. Tap the button labelled "Tap"

[PushHang2.zip](https://github.com/siteline/swiftui-introspect/files/14336425/PushHang2.zip)

### Version information

1.1.2

### Destination operating system

iOS 17.2

### Xcode version information

Xcode 15.2 (15C500b)

### Swift Compiler version information

```shell
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

**Comment by wtmoose** [comment]
Forgot to mention that removing the Introspect package from the sample project, without making any code changes, resolves the hang.

**Comment by davdroman** [comment]
I narrowed down the bug to `SignInWithAppleButton.swift`. These `public static let` declarations are causing the hang:

```swift
extension iOSViewVersion<SignInWithAppleButtonType, ASAuthorizationAppleIDButton> {
    @available(*, unavailable, message: "SignInWithAppleButton isn't available on iOS 13")
    public static let v13 = Self.unavailable()
    public static let v14 = Self(for: .v14)
    public static let v15 = Self(for: .v15)
    public static let v16 = Self(for: .v16)
    public static let v17 = Self(for: .v17)
}
```

I don't know why, and since it used to work in older Swift/Xcode/iOS versions I think this is a regression in either or several of those. Very annoying. I'll try to work out a fix and if I can't I'll sadly have to remove that implementation.

**Comment by wtmoose** [comment]
Thanks for investigating. That’s so weird. Just so you know, we had to replace Introspect with our own workaround to get unblocked. We’d like to bring it back in. But if you’re thinking of waiting to see if it resolves itself in a future version of Xcode, it won’t be a problem for us.

**Comment by davdroman** [comment]
@wtmoose understandable. Just so you know [1.1.3](https://github.com/siteline/swiftui-introspect/releases/tag/1.1.3) is out with the fix. Didn't make sense to sacrifice the entire library because of one minor introspection type wrecking havoc.

**Comment by wtmoose** [comment]
Great! Appreciate your help

**Comment by davdroman** [comment]
@philprime the thing is that the mere act of declaring that implementation makes the app hang when linking the library. So this is way too dangerous to even offer, even in a side branch.

**Comment by jdaites** [comment]
This might be related, but i'm finding that a similar thing is happening when introspecting inside a `navigationDestination`.

I'm doing this:

```
.introspect(.navigationStack, on: .iOS(.v16, .v17), scope: .ancestor) { navigationController in }
```

And when i add a print statement inside it just loops the print statement. Also CPU going to 99%. On version 1.1.3.
