### ISSUE TITLE
 Open PlatformEntity like .iOS(.v13...) generates an error

### ISSUE THREAD

**Issue by ramunasjurgilas** [siteline/swiftui-introspect#402]
### Description

In the source code I have found, that platform can be specified with open range like this: **.iOS(.v13...)**.

### Source code:
```
struct ContentView: View {
    var body: some View {
        ScrollView {
            // ...
        }
        .introspect(.scrollView, on: .iOS(.v13...)) { scrollView in
            // ...
        }
    }
}
```

### Getting this error:
Cannot convert value of type '()' to expected argument type 'PlatformViewVersion<iOSVersion, ScrollViewType, PlatformSpecificEntity>'

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Expected behavior

It must to compile without an error.

### Getting this error:
Cannot convert value of type '()' to expected argument type 'PlatformViewVersion<iOSVersion, ScrollViewType, PlatformSpecificEntity>'

### Add this code to the source code:
```
        .introspect(.scrollView, on: .iOS(.v13...)) { scrollView in
            // ...
        }
```

### Version information

1.1.2

### Destination operating system

iOS17 & iOS16

### Xcode version information

Version 15.2 (15C500b)

### Swift Compiler version information

```shell
arm64-apple-macosx14.0
```

**Comment by davdroman** [comment]
https://github.com/siteline/swiftui-introspect/issues/354#issuecomment-1712177770
