### ISSUE TITLE
privacy manifest required

### ISSUE THREAD

**Issue by frankois1234** [siteline/swiftui-introspect#406]
See https://github.com/pointfreeco/swift-composable-architecture/discussions/2559#discussioncomment-8005185

I don't believe SwiftUIIntrospect leverages any APIs that require a privacy manifest, and it definitely doesn't collect any user data. Correct me if I'm wrong though.

_Originally posted by @davdroman in https://github.com/siteline/swiftui-introspect/discussions/398#discussioncomment-8262451_

**Comment by frankois1234** [comment]
Sorry, but even the SDK collect no data, the sdk must contain the manifest which say explicitly it doesn't collect data. Even RxSwift must contain the maniest

**Comment by iharkatkavets** [comment]
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"

**Comment by benMohamed** [comment]
I'm getting emails back from Apple about this because your library is not compliant.

> ITMS-91053: Missing API declaration - Your app’s code in the “YourApp” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by davdroman** [comment]
`UserDefaults` is not used anywhere in this library.

**Comment by benMohamed** [comment]
@davdroman to reproduce it, create an empty project, integrate SwiftUI-Introspect, and then attempt to publish it. Within a few minutes, you will automatically receive that email from Apple

**Comment by Muhammadbarznji** [comment]
@davdroman, you're absolutely right. While the core functionality of the package doesn't rely on UserDefaults, I discovered that the SimulatorStatusMagic dependency actually utilizes UserDefaults.

**Comment by chrisvasselli** [comment]
@davdroman maintainer of SSM here, I'm just getting into this via a ping from @Muhammadbarznji (thanks again!). My assumption is that as a framework that's not shipped with the product, but just used for testing, I don't need to worry about the privacy manifest. Does that sound right? Was your fix just to remove it from release builds of SwiftUIIntrospect? Trying to figure out if I need to do anything more here.
