### ISSUE TITLE
Latest OS support

### ISSUE THREAD

**Issue by GeorgeElsham** [siteline/swiftui-introspect#419]
### Description

The platform versions need to be updated for the latest OSes.

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Version information

1.1.4

### Destination operating system

iOS 18

**Comment by ArchiProger** [comment]
Me too

**Comment by liamcharger** [comment]
Just opened a PR: #420
