### ISSUE TITLE
Setting scrollview delegate on List breaks cells update

### ISSUE THREAD

**Issue by SparklingAir** [siteline/swiftui-introspect#426]
### Description

Looks like it doesn't want to update cells correctly after setting the scroll view delegate through Introspect.
```
import SwiftUI
import Combine
import SwiftUIIntrospect

struct CellModel {
    let id: String
    let title: AnyPublisher<String, Never>
    
    init(id: String, title: String) {
        self.id = id
        self.title = CurrentValueSubject(title).eraseToAnyPublisher()
    }
}

struct Cell: View {
    private let model: CellModel
    
    @State private var title = "unchanged"
    
    init(_ model: CellModel) {
        self.model = model
    }
    
    var body: some View {
        Text(title)
            .onReceive(model.title) { value in
                title = value
            }
    }
}

struct ContentViewModel {
    let cells: [CellModel]
    init() {
        var tmp: [CellModel] = []
        for index in 0...10 {
            tmp.append(.init(
                id: UUID().uuidString,
                title: String(index)
            ))
        }
        cells = tmp
    }
}

struct ContentView: View {
    private let model: ContentViewModel
    
    private let delegate = ScrollViewDelegate()
    
    init(_ model: ContentViewModel) {
        self.model = model
    }
    
    var body: some View {
        List {
            ForEach(model.cells, id: \.id) { model in
                Cell(model)
            }
        }
        .introspect(.scrollView, on: .iOS(.v15, .v16, .v17)) { scrollView in
            scrollView.delegate = delegate
        }
    }
}

private class ScrollViewDelegate: NSObject, UIScrollViewDelegate {}

```

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Expected behavior

<img width="347" alt="Screenshot 2024-07-15 at 17 13 28" src="https://github.com/user-attachments/assets/b9f34375-6a1e-45cf-8d86-868b41ddf5d3">

### Actual behavior

<img width="338" alt="Screenshot 2024-07-15 at 17 13 48" src="https://github.com/user-attachments/assets/04ec3606-bfd2-47c3-89a0-cf52604828e8">

### Steps to reproduce

1. Create simple SwiftUI project
2. Replace the code of ContentView with the above code
3. Run and see the actual behaviour (screenshot above)
4. Comment the introspect modifier and see the expected behaviour (screenshot above)

### Destination operating system

Simulator iPhone 15 Pro - 17.2

### Xcode version information

15.1

**Comment by davdroman** [comment]
https://github.com/siteline/swiftui-introspect/issues/379#issuecomment-1774095315

**Comment by SparklingAir** [comment]
@davdroman Thank you, it makes sense. But it's still not clear to me how the delegate can prevent the cells from firing their .onReceive, .onAppear, .onChange and .task methods when they are already drawn on the screen.

Perhaps someone knows how to set up the delegate to solve the problem of updating cells?

**Comment by xvicient** [comment]
Hey, 

It's happening the same to me. I guess the problem arises because the custom delegate doesn't forward delegate methods to the original delegate that SwiftUI set up. That original delegate is responsible for reloading data when the underlying data changes. If we replace it without forwarding, the List doesn't know how to update anymore.

Since the are no active maintainers, I don't expect a fix for that, right?
