### ISSUE TITLE
When Modal is dismissed keyboard comes back up and down

### ISSUE THREAD

**Issue by MichaelMifsudSweeney** [siteline/SwiftUI-Introspect#43]
Hey there! 

I'm trying to implement Introspect to focus on a textfield when a modal appears. It works great when the modal appears! However, when I dismiss the modal, the keyboard initially dismisses until the modal is fully gone, then comes back up and down on the ContentView.

running Xcode 11.5

Put together a quick setup so you can see what I'm doing:

https://github.com/MichaelMifsudSweeney/SwiftUI-Introspect-Modal-Bug

**Comment by vukrado** [comment]
You can set a flag so `textField.becomeFirstResponder()` is only called once.

**Comment by zeidiao** [comment]
I have the same problem. Is there something I miss.?

**Comment by JannThomas** [comment]
Hi, as @vukrado has pointed out you can fix it like this:

```
struct ModalView : View {
    
    @State private var usernmae =  "hello"
    @State private var password =  "password"
    @State var shouldBecomeFirstResponder = true
    
    var body : some View {
        VStack(alignment: .leading) {
            Text("hello!")
            TextField("test", text: $usernmae)
                .introspectTextField { textField in
                    if shouldBecomeFirstResponder {
                        textField.becomeFirstResponder()
                        shouldBecomeFirstResponder = false
                    }
                }
            
        }
        .padding(.horizontal, 50)
        
    }
}
```

That said this has never been an issue with Introspect and I will close this issue now.
