### ISSUE TITLE
Introspecting ScrollView when running iOS 14 provides a UIFieldEditor or UITextView

### ISSUE THREAD

**Issue by hipwelljo** [siteline/SwiftUI-Introspect#44]
Both of which must be UIScrollViews but not the intended scroll view. ha

        ScrollView {
            //VStack including Text, TextField, and UITextField, UITextView (UIViewRepresentable)
        }
        .introspectScrollView() { scrollView in
            print(scrollView) //is UIFieldEditor or UITextView instead of UIScrollView in iOS 14
        }

    <UITextView: 0x7fa20615b000; frame = (0 0; 343 22); text = ''; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000003d44b0>; layer = <CALayer: 0x600000dab520>; contentOffset: {0, 0}; contentSize: {343, 22}; adjustedContentInset: {0, 0, 0, 0}>
    <UIFieldEditor: 0x7fa20611c600; frame = (0 0; 343 22); text = ''; clipsToBounds = YES; opaque = NO; gestureRecognizers = <NSArray: 0x6000003e8750>; layer = <CALayer: 0x600000daea60>; contentOffset: {0, 0}; contentSize: {343, 22}; adjustedContentInset: {0, 0, 0, 0}>

**Comment by JannThomas** [comment]
Hi @hipwelljo,

We have made some changes to the scroll view introspection and believe this should be fixed. Can you confirm that?

**Comment by hipwelljo** [comment]
I’m no longer using this in my project so cannot confirm but will go ahead and close if you believe it is indeed resolved :)
