### ISSUE TITLE
how to use Introspect.findAncestor in new version if the library

### ISSUE THREAD

**Issue by X901** [siteline/SwiftUI-Introspect#443]
### Description

Hi, 

I'm still on old version of the library 
I did ask it before here
https://github.com/siteline/swiftui-introspect/discussions/404

also someone else ask similar question here
https://github.com/siteline/swiftui-introspect/discussions/403

and we don't get any answer so I decide to ask it here

I want to update my code to use the new version
but I don't know how to update my code as I cannot find  
`Introspect.findAncestor `
in the new version 

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

**Comment by sergeirr** [comment]
@X901 You can try this, just do not forget to specify platform version

```swift
List { }
.introspect(.list, on: .iOS(.v18)) { collectionView in
    collectionView.refreshControl = UIRefreshControl()
}
```

**Comment by sergeirr** [comment]
@X901 Do not forget to specify platform version, introspect will work only on version you set by:
```swift
on: .iOS(.v13, .v14)
```
or use this to support all versions starting any
```swift
on: .iOS(.v13...)
```

List was a UITableView on versions before iOS 16:
```swift
List { }
.introspect(.list, on: .iOS(.v13, .v14, .v15)) { tableView in
    tableView.refreshControl = UIRefreshControl()
}

List { }
.introspect(.list, on: .iOS(.v16, .v17, .v18)) { collectionView in
    collectionView.refreshControl = UIRefreshControl()
}
```
