### ISSUE TITLE
CPU usage at 100% when updating @Published CGFloat

### ISSUE THREAD

**Issue by fredz999** [siteline/SwiftUI-Introspect#45]
An app I am building requires that a UIScroller grid has its position updated by another 'master' UIScroller.
I am using Introspect to monitor the content offset of a master UIScroller which then updates a CGFloat in a store class from which a slave UIScroller updates its position. Currently ScrollViewProxy will permit users to go between grid items using the scrollTo function but this appears to be meant for users to 'jump' between large numbers of items - whereas I am trying to achieve continuous scrolling so the existing scrollTo isn't what Im looking for.

This actually works reasonably well to any visual indications, both the scrollers scroll smoothly but the cpu usage goes through the roof, really to the point where the app would just not be useable.

I suspect that I'm misusing the Introspect capability in some way, can anyone explain how I correctly expose things like the scrollViewDidScroll function from the UIScrollerDelegate and the UIScrollers contentOffset? Is the introspect something that should only be called once at the init of any control using it?

this is the code, just two Scrollers a store containing the @Published CGFloat and a coloredSquare struct that appears in each Scroller
code: 

```swift
//================================================
class UIScrollStore : ObservableObject {
    @Published var expFloat : CGFloat = .zero
}

struct ColoredSquare : View , Identifiable{
    var id = UUID()
    @State var red : Double
    var body: some View{
        return ZStack{
        Color(red: red, green: 1, blue: 0)
        }.frame(width: 30, height: 30)
    }
}

struct ScrollViewExample: View {
    var colorSquares = [ColoredSquare]()
    @ObservedObject var uIScrollStore = UIScrollStore()
    init() {
    makeScrollerRectangles()
    }
    mutating func makeScrollerRectangles(){
        for i in 0...100{
            let sq = ColoredSquare(red: Double(i)*0.01)
            self.colorSquares.append(sq)
        }
    }
    var body: some View {
        HStack {
            //================ MASTER SCROLLER ==============================
            ScrollView {
                LazyVStack{
                    ForEach(colorSquares){sq in
                        sq
                    }
                }
                .introspectScrollView { scrollView in
                scrollView.layer.backgroundColor = UIColor.red.cgColor
                uIScrollStore.expFloat = scrollView.contentOffset.y
                }
            }
            //================ SLAVE SCROLLER ==============================
            ScrollView {
                LazyVStack{
                    ForEach(colorSquares){sq in
                        sq
                    }
                }
                .introspectScrollView { scrollView in
                scrollView.layer.backgroundColor = UIColor.orange.cgColor
                scrollView.contentOffset.y = uIScrollStore.expFloat
                }
            }
        }
    }
}
```

**Comment by end3r117** [comment]
You should make UIScrollStore the UIScrollViewDelegate for the scroll views. Weak references. Set offsets while delegate. Don't ask for too much in the introspection closure. Just use it to get whatever references you need and become delegate. That way UIKit only has to send the values to one place.

**Comment by fredz999** [comment]
Thanks end3r117, I gave what you said go, what I did was:
1: make the store implement UIScrollViewDelegate
2: set the delegate of the master lazyHstack ScrollView as the store
3: NOT set the slave(2nd) lazyHstack ScrollView as the store
4: make a optional reference to the second scroller in the store
5: in the scrollViewDidScroll method of the store, update the slave grids content offset, see code below

struct ScrollViewSample: View {
    @ObservedObject var uIScrollStore : UIScrollStore
    var colorSquares = [CellContent]()
    
    init(storeParam : UIScrollStore) {
        self.uIScrollStore = storeParam
        makeScrollerRectangles()
    }
    
    mutating func makeScrollerRectangles(){
        for i in 0...50{
            let q = CellContent(place: i, red: Double(i)*0.02) //CellContent(red: Double(i)*0.02)
            self.colorSquares.append(q)
        }
    }
    
    var body: some View {
        return ZStack{
            VStack{
                ScrollView(.horizontal, showsIndicators: false)  {
                     
                        LazyHStack(alignment: .top, spacing: 3)  {
                            ForEach(colorSquares){ q in
                                q
                            }
                        }
                        .introspectScrollView { scrollView in
                            if uIScrollStore.delegateSet == false {
                                scrollView.delegate = uIScrollStore
                                uIScrollStore.delegateSet = true//this is to stop it getting set multiple times
                            }
                        }
                    
                }
                .frame(width: UIScreen.main.bounds.width-100, height: 120)
                .background(Color.red)
                //==========================================================================
                ScrollView(.horizontal, showsIndicators: false)  {
                        LazyHStack(alignment: .bottom, spacing: 3)  {
                            ForEach(colorSquares){ q in
                                q
                            }
                        }
                        .introspectScrollView { scrollView in
                            //again using nil check to stop getting set over and over
                            if uIScrollStore.slaveGrid == nil {
                                uIScrollStore.slaveGrid = scrollView
                            }
                        }
                }
                .frame(width: UIScreen.main.bounds.width-100, height: 30)
                .background(Color.blue)
                .disabled(true)
            }
        }
    }
    
}

class UIScrollStore : NSObject, ObservableObject,  UIScrollViewDelegate {
    var delegateSet : Bool = false
    var slaveGrid : UIScrollView?
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if let lclSlaveGrid = slaveGrid{
            lclSlaveGrid.contentOffset.x = scrollView.contentOffset.x
            lclSlaveGrid.isScrollEnabled = false
        }
    }
}

Now, this allows the positional updates I was trying to achieve and the cpu usage is around 4-7%
However if you'd be so kind, I have a few questions 
1: is 4-7% cpu usage still a bit high? what do you think?
2: I didn't use any weak vars, up till now on, say,  I would only use weak vars to stop leaking when a UICollectionViewCell  was reused with different UIKit components , the lazyHGris/stack seem to handle the reuse "under the hood" and instead rely on the user deriving them all from the data, is there anywhere you can see in that code where I should have used weak vars?
3: I take it that I use the lazyHGrid and lazyVGrid if I want rows and columns? I think I do tho I'll have to check .
Listen thanks for getting back to me man, I really appreciate that.

**Comment by fredz999** [comment]
Incidentally end3r117(or anyone else), that problem with the slave scrollView becoming able to scroll after its .isScrollEnabled being set to false, should I place that onto a separate ticket? I think it's maybe a separate problem, what do you think?

**Comment by JannThomas** [comment]
Hi, as long as the `.introspectScrollView()` function does work and returns the right `UIScrollView`, this issue is not in the scope of this project. That said I will close this issue now.
