### ISSUE TITLE
Cannot modify UITableView.separatorInset

### ISSUE THREAD

**Issue by LiYanan2004** [siteline/SwiftUI-Introspect#5]
I have written the code like this. 
<img width="597" alt="screenShot" src="https://user-images.githubusercontent.com/37542129/71764484-5d115800-2f23-11ea-953c-ea40fccd3248.png">

**Comment by Crysis21** [comment]
yup. not working here either

**Comment by SplittyDev** [comment]
Hi @LiYanan2004,

are you still experiencing this issue?
It seems that as of SwiftUI 2, `List` doesn't have an underlying UIKit `TableView` anymore.

**Comment by JannThomas** [comment]
Hi @LiYanan2004,

we were now able to replicate this behavior. The `UITableView` is introspected and other changes apply, but changing the insets doesn't do anything. 

That said, as this is not an Introspect bug and Introspects functionality is not broken, I will close this issue.
