### ISSUE TITLE
TextField.introspectTextField called many times causing high input latency

### ISSUE THREAD

**Issue by varunrau** [siteline/SwiftUI-Introspect#50]
I added a to my macOS app like so

```
                TextField("", text: $text)
                    .introspectTextField { textField in
                        textField.becomeFirstResponder()
                }
```
After adding the `introspectTextField` function, all interactions in my app are extremely slow (several seconds) and cause a rainbow spinner. If I add a print statement to the `introspectTextField` body, I can see that it is called many, many times.

Removing that function resolves the performance issues.

**Comment by vukrado** [comment]
You can put a flag so it only gets called once

**Comment by 19hours** [comment]
Any progress since then ? @varunrau
