### ISSUE TITLE
Introspect List

### ISSUE THREAD

**Issue by melgu** [siteline/SwiftUI-Introspect#51]
I want to use Introspect on a list which is using the SidebarListStyle. Using `introspectTableView` doesn't work.

**Comment by karapurakesh** [comment]
I am unable to remove the separator lines from the list. Is it working ? Any one can please respond .

**Comment by paulo2703** [comment]
Same issue here!

**Comment by lucastimeless** [comment]
Are you using iOS 14? If so this may fix it https://github.com/siteline/SwiftUI-Introspect/pull/56

**Comment by mikemike396** [comment]
@lucastimeless We tried #56 on introspectTableView and it didn't seem to work for line separator color.

     .introspectTableView { tableView in
        tableView.separatorColor = UIColor(named: "sectionSeparatorColor")
        tableView.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        tableView.tableFooterView = UIView()
        let refreshControl = UIRefreshControl()
        refreshControl.addTarget(self.viewModel.self, action: #selector(self.viewModel.pullToRefresh), for: .valueChanged)
        tableView.refreshControl = refreshControl
        self.viewModel.refreshControl = refreshControl
     }

**Comment by melgu** [comment]
> Are you using iOS 14? If so this may fix it #56, haven't tested it with `List` though, only `ScrollView`

In my case, using introspectScrollView instead of tableView did work. Thanks!

**Comment by kandelvijaya** [comment]
SwiftUI on macOS:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<SwiftUI._NSGraphicsView 0x12aa66230> has reached dealloc but still has a super view. Super views strongly reference their children, so this is being over-released, or has been over-released in the past.'
terminating with uncaught exception of type NSException
```

**Comment by karapurakesh** [comment]
Add below modifiers to ForEach for removing separators of List. It should work.

            .padding(.horizontal)
            .padding(.vertical, 5)
            .listRowInsets(EdgeInsets())
            .background(Color(UIColor.systemBackground))

**Comment by JannThomas** [comment]
@karapurakesh Please open a new issue if this still happens and is not related to this issue.

**Comment by JannThomas** [comment]
@melgu Can you confirm this is still an issue? If so, please provide a sample view. I have tested it and it works for me.

**Comment by JannThomas** [comment]
As you have not replied within a week I will close this issue for now. Please reopen it if you still experience this issue.

**Comment by melgu** [comment]
@JannThomas Sorry for my late reply. `.introspectTableView` does generally work.
It doesn't work as I expected it to when trying to make it the first responder, but using `.introspectScrollView` worked for that case.

**Comment by SplittyDev** [comment]
@melgu can you provide example code where this issue happens? From the description it's not clear what exactly isn't working.

**Comment by melgu** [comment]
If I replace `.introspectScrollView` with `.introspectTableView` [here](https://github.com/melgu/TidalSwift/blob/0f8851f9825e896e6afc3ffacd224875cbf44228/TidalSwift/Top-Level%20Views/TopDetailView.swift#L77), it doesn't focus the list anymore. Unlike the image, the selected item stays gray. I know, it's a really specific issue, so if you can't comment on that, it's absolutely fine – especially as it works when using `.introspectScrollView`.

<img width="135" alt="List" src="https://user-images.githubusercontent.com/9601403/112512388-9dacf980-8d93-11eb-9d52-b8309de37042.png">
