### ISSUE TITLE
Outdated release

### ISSUE THREAD

**Issue by DanDolog** [siteline/SwiftUI-Introspect#53]
Version 0.1.0 doesn't contains fixes for mac Catalyst support. Please release new version

**Comment by ldiqual** [comment]
Fair point. I'm having issues registering with the cocoapods trunk at the moment, but in the meantime feel free to use the master branch in your podfile. I should be getting access back within the next couple days, then I'll push a new release. Thanks for your patience!

**Comment by JannThomas** [comment]
This is already solved so I will close this issue.
