### ISSUE TITLE
Compiler Error only when archiving

### ISSUE THREAD

**Issue by elai950** [siteline/SwiftUI-Introspect#57]
I'm trying to archive my app, but for some reason I'm getting this errors:

![צילום מסך 2020-10-14 ב-20 15 42](https://user-images.githubusercontent.com/37900883/96022880-38ef8980-0e5a-11eb-9b2d-54fffe956050.png)

Happens when I'm archiving or when just building using Any iOS Device.
Tried deleting my derived folder, uninstall Cocoapods and reinstall all the pods.
Nothing works.

Does any one have an idea?

**Comment by JannThomas** [comment]
Hi, can you still reproduce this on the current master? 

I have tried this and it worked for me. If you can reproduce this, please reopen this issue and attach an Xcode project that showcases this behavior. I can imagine it having to do with how you import SwiftUI, but without seeing it for myself I cannot give you any further support.
