### ISSUE TITLE
Request: ColorPicker support

### ISSUE THREAD

**Issue by ConfusedVorlon** [siteline/SwiftUI-Introspect#59]
ColorPicker is a UIColorWell underneath (in iOS anyway)

**Comment by ConfusedVorlon** [comment]
this covers the iOS side

    @available(iOS 14.0, *)
    public func introspectColorWell(customize: @escaping (UIColorWell) -> ()) -> some View {
        return inject(UIKitIntrospectionView(
            selector: { introspectionView in
                guard let viewHost = Introspect.findViewHost(from: introspectionView) else {
                    return nil
                }
                return Introspect.previousSibling(containing: UIColorWell.self, from: viewHost)
            },
            customize: customize
        ))
    }

**Comment by JannThomas** [comment]
This was added in #87.
