### ISSUE TITLE
TextField.introspectTextField not calling

### ISSUE THREAD

**Issue by natew** [siteline/SwiftUI-Introspect#6]
XCode 11.3, new project, code like this:

```swift
TextField(
                        hasTags ? "" : self.placeholder,
                        text: self.$searchText,
                        onEditingChanged: self.handleEditingChanged,
                        onCommit: {
                            print("onCommit")
                        }
                    )
                        .introspectTextField { textField in
                            print("we got a text field here \(textField)")
                    }
```

When I run it works as expected, but `we got a text field here` never logs/runs.

**Comment by gbreen12** [comment]
+1

**Comment by beeef** [comment]
Having the same issue. With some TextFields it's working and with some it's not. 

```
TextField("Search ...", text: self.$searchText, onEditingChanged: { _ in
   self.showCancelButton = true
})
   .foregroundColor(.primary)
   .introspectTextField { (textField) in
         textField.becomeFirstResponder()
   }
```

The keyboard won't show up on this textfield ...

**Comment by beeef** [comment]
At first I thought it may be because I'm presenting a new view, and maybe the `.becomeFirstResponder()` does not work while the presenting transition is going on. But that's not the problem, I tested it.

**Comment by ldiqual** [comment]
Can someone provide a working example with the complete view code? I can't reproduce locally

**Comment by Phineas** [comment]
Hey guys, make sure your `introspectTextField` is AFTER your styles, as order of modifiers is important in SwiftUI!

Example:

```swift
TextField("", text: $text)
                .padding(15)
                .background(Color("LayoutLight"))
                .cornerRadius(10)
                .font(Font.system(size: 20, weight: .semibold))
                .accentColor(Color("Brand"))
                .foregroundColor(Color("TextLightest"))
                .introspectTextField { textField in
                    textField.becomeFirstResponder()
                }
```

**Comment by Phineas** [comment]
Hey guys, make sure your `introspectTextField` is AFTER your styles, as order of modifiers is important in SwiftUI!

Example:

```swift
TextField("", text: $text)
    .padding(15)
    .background(Color("LayoutLight"))
    .cornerRadius(10)
    .font(Font.system(size: 20, weight: .semibold))
    .accentColor(Color("Brand"))
    .foregroundColor(Color("TextLightest"))
    .introspectTextField { textField in
        textField.becomeFirstResponder()
     }
```

**Comment by stammy** [comment]
Likewise this does not work for me either, even with it at the end of my styles

**Comment by lopify** [comment]
+1

**Comment by neywen** [comment]
I faced the same problem here.
I've decided to break my View piece by piece until I found out what's involved.
And - I want to add 'obviously' - the last-little-thing-I-could_ever_think_of was responsible : the .cornerRadius modifier.

It may not be related to this modifier specifically, but I can reproduce the problem using this case.
I've pushed a minimal Xcode project to reproduce the bug, if it's any help:
https://github.com/neywen/test-introspector

**Comment by codetheweb** [comment]
In my case, I was able to solve this by doing `.introspectTextField` *after* `.cornerRadius`.

**Comment by ibash** [comment]
I have discovered something - sometimes swiftui uses an NSTextField and sometimes it uses an NSTextView, maybe that's affecting introspect?

**Comment by paulo2703** [comment]
+1

**Comment by barryllium** [comment]
+1

**Comment by tarassh** [comment]
+1

**Comment by x4080** [comment]
Hi, .cornerRadius is the culprit, but it still affecting intospect even if its after the textField

```
HStack {
                TextField("Content", text: $content)
                    .introspectTextField { textField in
                        print("debug")
                        textField.becomeFirstResponder()
                }
            }
            .background(Color.red)
            .cornerRadius(20)
```

Above code won't print debug or becomeFirstResponder if cornerRadius is not remarked

How to solve it ?

TIA

**Comment by barryllium** [comment]
> Hi, .cornerRadius is the culprit, but it still affecting intospect even if its after the textField
> 
> ```
> HStack {
>                 TextField("Content", text: $content)
>                     .introspectTextField { textField in
>                         print("debug")
>                         textField.becomeFirstResponder()
>                 }
>             }
>             .background(Color.red)
>             .cornerRadius(20)
> ```
> 
> Above code won't print debug or becomeFirstResponder if cornerRadius is not remarked
> 
> How to solve it ?
> 
> TIA

Move your introspect line below cornerRadius. It will technically be attached to the HStack, but it will affect the TextField.

**Comment by x4080** [comment]
```
HStack {
                TextField("Content", text: $content)
                   
                }
            }
            .background(Color.red)
            .cornerRadius(20)
            .introspectTextField { textField in
                        print("debug")
                        textField.becomeFirstResponder()
```

You mean like above ? I think I did try that and xcode wont compile (I'll try again if its what you mean)

**Comment by barryllium** [comment]
That won't compile because you also need to move a brace down.

**Comment by x4080** [comment]
@barryllium My mistake it works now

```
HStack {
            TextField("Content", text: $content)
            
        }
        .background(Color.red)
        .cornerRadius(20)
        .introspectTextField { textField in
            print("debug")
            textField.becomeFirstResponder()
        }
```

Thanks

**Comment by SplittyDev** [comment]
@natew confirmed, this is definitely broken right now.

**Comment by dinesharjani** [comment]
I can confirm this remains an issue - in particular on iOS. On macOS my NSTextField was still being introspected.

However, I checked my SwiftUI hierarchy and found an upper cornerRadius modifier - after switching them up I got the call on iOS. Thanks to all who contributed this fix / hack.
