### ISSUE TITLE
SwiftUI: Tabbar doesn't appear again after hiding it.

### ISSUE THREAD

**Issue by KLukas04** [siteline/SwiftUI-Introspect#60]
Hi, I use Introspect to hide my Tabbar in one of my subviews. That works really great but when I go back the Tabbar is still hidden. But I added the modifier that the Tabbar should appear again / be visible. 
Does someone have a solution?

**Comment by timothyerwin** [comment]
I can confirm this is broken now too..seems to be since the last update

**Comment by timothyerwin** [comment]
it might actually be an issue with the lastest swift or ios...I got around it by setting an instance of the UITabBarController in the view and then just referencing that in onAppear

**Comment by JannThomas** [comment]
@timothyerwin's solution is nice and the way to go everywhere.
