### ISSUE TITLE
UISplitViewController Introspection

### ISSUE THREAD

**Issue by a-shatou** [siteline/SwiftUI-Introspect#70]
I tried to do this:

```
extension View {
    public func introspectSplitViewController(customize: @escaping (UISplitViewController) -> ()) -> some View {
        return inject(UIKitIntrospectionViewController(
            selector: { introspectionView in
                guard let viewHost = Introspect.findViewHost(from: introspectionView) else {
                    return nil
                }
                return Introspect.previousSibling(containing: UISplitViewController.self, from: viewHost)
            },
            customize: customize
        ))
    }
}
```
But I got this error:
`Cannot convert value of type 'UIViewController' to expected argument type 'PlatformView' (aka 'UIView')`

What I am doing wrong?

**Comment by gojosh** [comment]
I was able to get it to compile with the following:

```
extension View {
    public func introspectSplitViewController(customize: @escaping (UISplitViewController) -> ()) -> some View {
        return inject(UIKitIntrospectionViewController(
            selector: { introspectionViewController in
                
                // Search in ancestors
                if let splitViewController = introspectionViewController.splitViewController {
                    return splitViewController
                }
                
                // Search in siblings
                return Introspect.previousSibling(containing: UISplitViewController.self, from: introspectionViewController)
            },
            customize: customize
        ))
    }
}
```
But, it doesn't appear to actually do anything when I use it:

```
.introspectSplitViewController { splitViewController in
                splitViewController.minimumPrimaryColumnWidth = CGFloat(400)
                splitViewController.preferredPrimaryColumnWidth = CGFloat(400)
                // splitViewController.preferredPrimaryColumnWidthFraction = CGFloat(0.5)
}
```

It still displays the primary column at the default 320 pts wide. Let me know if I'm missing something...

**Comment by gojosh** [comment]
Update: It turns out the issue was caused by not explicitly setting the maximumPrimaryColumnWidth. Also, the modifier needs to be put on an element inside of the NavigationView, not on the NavigationView itself.

```
.introspectSplitViewController { splitViewController in
    splitViewController.preferredPrimaryColumnWidth = 375
    splitViewController.minimumPrimaryColumnWidth = 375
    splitViewController.maximumPrimaryColumnWidth = 400
}
```

**Comment by a-shatou** [comment]
Thank you. It works like a charm.

> I was able to get it to compile with the following:
> 
> 
> 
> ```
> 
> extension View {
> 
>     public func introspectSplitViewController(customize: @escaping (UISplitViewController) -> ()) -> some View {
> 
>         return inject(UIKitIntrospectionViewController(
> 
>             selector: { introspectionViewController in
> 
>                 
> 
>                 // Search in ancestors
> 
>                 if let splitViewController = introspectionViewController.splitViewController {
> 
>                     return splitViewController
> 
>                 }
> 
>                 
> 
>                 // Search in siblings
> 
>                 return Introspect.previousSibling(containing: UISplitViewController.self, from: introspectionViewController)
> 
>             },
> 
>             customize: customize
> 
>         ))
> 
>     }
> 
> }
> 
> ```
> 
> But, it doesn't appear to actually do anything when I use it:
> 
> 
> 
> ```
> 
> .introspectSplitViewController { splitViewController in
> 
>     splitViewController.minimumPrimaryColumnWidth = CGFloat(400)
> 
>     splitViewController.preferredPrimaryColumnWidth = CGFloat(400)
> 
>     // splitViewController.preferredPrimaryColumnWidthFraction = CGFloat(0.5)
> 
> }
> 
> ```
> 
> 
> 
> It still displays the primary column at the default 320 pts wide. Let me know if I'm missing something...

**Comment by ldiqual** [comment]
@a-shatou Neat! Would you be willing to add this method to Introspect via a pull request? I'd be happy to review it and merge it.

**Comment by a-shatou** [comment]
> @a-shatou Neat! Would you be willing to add this method to Introspect via a pull request? I'd be happy to review it and merge it.

I would love to do it but get sucked in a project - don't have the time. Thanks again though for your effort - it worked fine :)
