### ISSUE TITLE
Problem when applying filters on a ScrollView ancestor

### ISSUE THREAD

**Issue by Saturnyn** [siteline/SwiftUI-Introspect#73]
Hi,
I'm using the lib in order to access and control the behaviour of a ScrollView in my app.
I works very well and makes it possible to work around SwiftUI's limitations.
However, I have a problem when applying a filter such as _saturation()_ on the root view of my app.
It seems like doing this "breaks" something and _introspectScrollView()_ is not called anymore.

The structure of the app is fairly complex with a lot of nesting, but the issue can be reproduced in a simpler example:

```swift
struct ContentView: View {
	@State var hasScrollView:Bool = false
	
	var body: some View {
		VStack{
			Text("Has ScrollView: \(hasScrollView ? "True":"False")")
			ScrollView{
				VStack{
					ForEach((1...50), id: \.self) {
						item($0)
					}
				}
			}
			.introspectScrollView{ scrollView in
				hasScrollView = true
			}
		}
		//hasScrollView is only true if we remove this
		.saturation(0)
	}
	
	func item(_ value:Int)->some View{
		HStack{
			Text("\(value)")
			Spacer()
		}
		.border(Color.red)
		.padding(10)
	}
}
```

_Note:_ After doing some testing, it looks like moving the introspectScrollView() block after the saturation() call fixes the problem, but it would be quite messy to do it like this in the actual app, as it would mean having the introspectScrollView() and the code that relies on it at a different level and in different files.

Any insight would be greatly appreciated.

**Comment by Saturnyn** [comment]
Update:

I found a workaround that is not ideal but solves my problem for now.
I am using this:
```
extension View {
	public func introspectScrollView2(customize: @escaping (UIScrollView) -> ()) -> some View {
		return inject(UIKitIntrospectionView(
			selector: { introspectionView in
				guard let viewHost = Introspect.findViewHost(from: introspectionView) else {
					return nil
				}
				if let scrollView = Introspect.previousSibling(containing: UIScrollView.self, from: viewHost) {
					return scrollView
				}else if let superView = viewHost.superview {
					//When there is a filter such as saturation() applied on the ancestors, it changes the hierarchy a bit, and we may find the scrollview like this instead
					return Introspect.previousSibling(containing: UIScrollView.self, from: superView)
				}
				return nil
			},
			customize: customize
		))
	}
}
```

It is a very brittle solution, but I guess it comes with the territory when using SwiftUI :/

**Comment by davdroman** [comment]
This is now fixed as mentioned here: https://github.com/siteline/SwiftUI-Introspect/issues/154#issuecomment-1611815775 (it says blur, but all of the filters work now including saturation).
