### ISSUE TITLE
Use macOS 11 on CI

### ISSUE THREAD

**Issue by SplittyDev** [siteline/SwiftUI-Introspect#75]
CircleCI currently doesn't support macOS 11.
Github CI current doesn't support macOS 11.

As soon as they do, we should upgrade and make sure that macOS11-specific test cases run as part of CI.

CircleCI Discussion:
https://discuss.circleci.com/t/macos-11-big-sur-status-update/39204

GitHub Discussion:
https://github.com/actions/virtual-environments/issues/1814
https://github.com/actions/virtual-environments/issues/2486

**Comment by davdroman** [comment]
Done #185.
