### ISSUE TITLE
Plan to support macOS/AppKit ?

### ISSUE THREAD

**Issue by dreampiggy** [siteline/SwiftUI-Introspect#8]
Hi, I'm author of [SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI), which is a full cross-platform (iOS/tvOS/macOS/watchOS/macCatalyst) image loading framework for SwiftUI.

Recentlly I use the introspect framework to test the View of that framework. Which is one `UIViewRepresentable` and `NSViewRepresentable`

However, seems this framework does not works on macOS/AppKit, any plan to update ? I found it's not so hard to implements. You should just change the API with `NSHostingView`, there are small differenences between UIKit/AppKit for SwiftUI corporate.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/73155682-62bf1f80-4116-11ea-8d31-639b47ee7bc3.png)

**Comment by dreampiggy** [comment]
For people who need macOS && tvOS support, I create a folk and release v0.1.0 version:

[dreampiggy/SwiftUI-Introspect](https://github.com/dreampiggy/SwiftUI-Introspect/releases/tag/0.1.0)

**Comment by kaishin** [comment]
This would be quite useful to add.

**Comment by ldiqual** [comment]
This is now available on cocoapods, version 0.1.0
