### ISSUE TITLE
it's can't use on list?

### ISSUE THREAD

**Issue by flystaros** [siteline/SwiftUI-Introspect#97]
it's can't use on list, why?

**Comment by SplittyDev** [comment]
Hi @flystaros, could you provide some example code?

We support introspecting Lists (both `UITableView` and `NSTableView`), so this should definitely work. I can't really help you though without some code to look at.

**Comment by JeremPlln** [comment]
Hey, there's a related topic [here](https://github.com/siteline/SwiftUI-Introspect/issues/110) waiting for a reply from the developers. It seems that introSpect doesn't work on List.

**Comment by davdroman** [comment]
See my answer in #110.
