### ISSUE TITLE
ScrollView Introspection still not working

### ISSUE THREAD

**Issue by chrysb** [siteline/SwiftUI-Introspect#98]
**Introspect 0.1.3**
**XCode 12.4**

Hi folks!

I noticed that I am not able to use `introspectScrollView` to disable scrolling as I had hoped. I saw `0.1.3` might have fixed the issue, but it still seems like it's not hitting that codepath. Here's my code...

```
      ScrollView(.horizontal, showsIndicators: false) {
         // ....
      }
      .introspectScrollView { scrollView in
        print("Introspect scrollview")
        scrollView.isScrollEnabled = false
      }
```

Nothing prints and if I put a breakpoint there it doesn't hit it.

**Comment by schazers** [comment]
I am seeing the same behavior. All ScrollView properties are no-ops, e.g. ```scrollView.isUserInteractionEnabled = false``` does not work.

**Comment by chrysb** [comment]
If it's helpful, here's some code I have to introspect a `UIScrollView` from a `UIHostingController` that has been working:

```
  func findUIScrollView(view: UIView?) -> UIScrollView? {
    if view?.isKind(of: UIScrollView.self) ?? false {
      return (view as? UIScrollView)
    }
    
    for v in view?.subviews ?? [] {
      if let vc = findUIScrollView(view: v) {
        return vc
      }
    }
    
    return nil
  }
```

**Comment by JannThomas** [comment]
Hi @chrysb, 

Do all tests run successfully for you? This scenario is represented there and works for me both on 0.1.3 and on master. 

You can also try putting this on a child of the ScrollView, which is less error-prone. If that still doesn't work, please provide some more source code since the one you provided works for me.

**Comment by chrysb** [comment]
Adding it to a child of the ScrollView seems to work. Thanks so much!
