### ISSUE TITLE
View.cornerRadius prevents introspectTextField from working

### ISSUE THREAD

**Issue by LinnierGames** [siteline/SwiftUI-Introspect#99]
Introspect 0.1.3
Xcode 12.4

Hey y'all!

Similar to #6 `introspectTextField` is not being called when the `cornerRadius` modifier is applied to an ancestor. Here's a simplified example of my scenario:
```
struct AppContentScreen: View {
    @State var urlTextField: UITextField?

    var body: some View {
        ZStack {
            Rectangle()
                .foregroundColor(.pink)
                .ignoresSafeArea()

            VStack {
                VStack {
                    Text("Title")
                    TextField("", text: .constant("Foobar"))
                        .background(Color.yellow)
                }
                .padding()
                .background(Color.white)
                .cornerRadius(8)

                VStack {
                    Text("URL")
                    TextField("", text: .constant(""))
                        .background(Color.yellow)
                        .introspectTextField { (tf) in
                            urlTextField = tf
                        }
                    Divider()
                    Text("Foobar text here")
                    Divider()
                    Text("Price")
                    TextField("", text: .constant(""))
                        .background(Color.yellow)
                }
                .padding()
                .background(Color.white)
                .cornerRadius(8)

                Button("Show Keyboard for URL") {
                    urlTextField?.becomeFirstResponder()
                }
            }
            .frame(width: 250)
        }
    }
}
```

![Screen Shot 2021-04-03 at 10 20 28 AM](https://user-images.githubusercontent.com/1758210/113486184-4f1fef00-9466-11eb-8aff-07ced8cf9a2f.png)

After reading the issue, it was suggested to apply the `introspectTextField` modifier after the `cornerRadius` modifier but this doesn't help since there's more than one `UITextField` descendants where the `cornerRadius` modifier is applied therefore the `UITextField` that's passed in the `introspectTextField`'s closure is the wrong text field (it's the _Password (again)_ text field that's passed)

Any thoughts? Please excuse the ugly coloring, it's indented for demo purposes 😆

**Comment by LinnierGames** [comment]
Oops might be a duplicate of #93, feel free to close

**Comment by JannThomas** [comment]
Yes it's the same issue. But thanks for the effort you put into this report. I will leave this open and close it with the PR for #93 when it is ready.

**Comment by chitvan832** [comment]
It also happens for `.introspectTextView`

**Comment by LinnierGames** [comment]
> Yes it's the same issue. But thanks for the effort you put into this report...

Of course 😁 nothing beats a bug report with not enough context 

For a quick solution, I've massaged the introspect methods to take in a filter therefore after it finds an instance of a UITextField, it would then check the filter before returning it. If false, the search continues to the next sibling

**Comment by davdroman** [comment]
This is the same as https://github.com/siteline/SwiftUI-Introspect/issues/119, which has since been [fixed](https://github.com/siteline/SwiftUI-Introspect/issues/119#issuecomment-1611747305) thanks to the new [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme) module. Closing.
